### ISSUE TITLE
when I call displayIncomingCall witth parameter video, it still shows audio in CallKit

### ISSUE THREAD

**Issue by jfojtl** [react-native-webrtc/react-native-callkeep#105]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description

No matter how I configure callkeep lib and call displayIncomingCall, it always shows "<app> audio". Our users expect to show video when it is video call and for example viber or whatsapp supprots that, so I think it is possible to do via CallKeep.

![IMG_3322](https://user-images.githubusercontent.com/958568/65392492-d5d61500-dd75-11e9-8eed-1c8d16a7f54b.PNG)

## Versions
    - Callkeep: 2.0.3
    - React Native: 0.58.6
    - iOS: 12.0, 12.1, 12.2, 13.0, 13.1beta
    - Android: -
    - Phone model: iPhone X, XS Max, XS, XR

## Logs

```
Paste here
```

**Comment by shavavo** [comment]
How did you resolve this issue?
