### ISSUE TITLE
checkReachability waking up app twice when calling while killed

### ISSUE THREAD

**Issue by bhuangy** [react-native-webrtc/react-native-callkeep#115]
# Bug report

- [X] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [X] Android

## Description
I'm a little confused on the flow using checkReachability. While the app is killed, and we initiate an outgoing call, we do not receive an event in JS telling us to call setReachable(), and so we tell the app to wake up after 2 seconds.
However, in makeOutgoingCall in VoiceConnectionService, we're already telling the app to wake up if the app is not in the Foreground  or we tell it to forceWakeUp.
```
// Wakeup application if needed
        if (!isForeground || forceWakeUp) {
            Log.d(TAG, "onCreateOutgoingConnection: Waking up application");
            this.wakeUpApplication(uuid, number, displayName);
        }
```
This is effectively waking the app up twice whenever we initiate an outgoing call while the app is killed. To me it seems checkReachability isn't needed. Is there something I'm missing in regards to its functionality?

## Steps to Reproduce
Make an outgoing call while the app is killed.

**Comment by manuquentin** [comment]
Hi @bhuangy is this still an issue ?
