### ISSUE TITLE
Type definition for supportsVideo

### ISSUE THREAD

**Issue by ElGatoLoco** [react-native-webrtc/react-native-callkeep#121]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [] Android
 - [*] iOS

## Description

`IOptions` interface defines ios option `supportsVideo` as strictly `false` and as such breaks tsc if the option value differs. 

## Steps to Reproduce

Define an object of type `IOptions` with the value of ios -> supportsVideo set to true.

## Versions
    - Callkeep: 3.0.6
    - React Native: 0.60.3

## Logs

```
43     supportsVideo: true,
       ~~~~~~~~~~~~~

  node_modules/react-native-callkeep/index.d.ts:20:5
    20     supportsVideo: false,
           ~~~~~~~~~~~~~
    The expected type comes from property 'supportsVideo' which is declared here on type '{ appName: string; imageName?: string | undefined; supportsVideo: false; maximumCallGroups: "1"; maximumCallsPerCallGroup: "1"; ringtoneSound?: string | undefined; }'


Found 1 error.
```

**Comment by manuquentin** [comment]
Fixed in #147
