### ISSUE TITLE
[iOS] displayIncomingCall throws an error: parameter 'localizedName' cannot be nil'

### ISSUE THREAD

**Issue by jasonkang14** [react-native-webrtc/react-native-callkeep#125]
# Bug report

- [#] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [#] iOS

## Description
When I call RNCallKeep.displayIncomingCall() using parameters described in the read me like below, I get an error saying that `parameter 'localizedName' cannot be nil'`

## Steps to Reproduce
this is how I called the method;
```
acceptCall = () => {
    const uuid = this.requestedUserUuid;   //     "0731961b-415b-44f3-a960-dd94ef3372fc",
    const handle = 'testemail@email.com'
    const localizedCallerName = 'testNickname';
    const handleType = 'email';
    const hasVideo = false;
    if (Platform.OS === 'android') {
      RNCallKeep.displayIncomingCall(uuid, handle, localizedCallerName);
    } else {
      RNCallKeep.displayIncomingCall(uuid, handle, handleType, hasVideo, localizedCallerName);
    }
  }
```

## Versions
    - Callkeep: 3.0.6
    - React Native: 0.50.0
    - iOS: 13.2
    - Android: N/A
    - Phone model: iPhone 11 

## Logs

![error](https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/73372371_10220306799921043_4309136710937083904_o.jpg?_nc_cat=101&_nc_oc=AQlyCVTUx0kgTKIChXcAUjBIPDyBX6aKi7e0L5XQW76T3-3lEdqRgD7qAseF__I-RIM&_nc_ht=scontent-icn1-1.xx&oh=7a31ac2bd3796235ca4556948dcb87fd&oe=5E60246F)

**Comment by jasonkang14** [comment]
there was a typo. the current version of react-native is `0.59.1`

**Comment by jasonkang14** [comment]
solved it by looking at issues that other people have opened

**Comment by ryanmcclure4** [comment]
@jasonkang14 Can you share which issues helped you to solve this?

**Comment by jasonkang14** [comment]
@ryanmcclure4 the problem was that I was not initializing `callkeep` in the screen in which I was using the method. after initializing `callkeep` it worked fine.

**Comment by ryanmcclure4** [comment]
Great, that solved it for me as well 🎊

**Comment by samad324** [comment]
i'm getting the same issue even i initialized callkeep.

```parameter 'UUID' cannot be nil' was thrown while```

**Comment by stoyan-frieze** [comment]
@samad324 I was getting the same issue as you because I was passing a random typed in string as an uuid while I was testing. I fixed it by passing a RFC4122 uuid generated with https://www.npmjs.com/package/react-native-uuid

**Comment by samad324** [comment]
yes, that works for me as well.
