### ISSUE TITLE
Unable to open display UI screen on incoming call 

### ISSUE THREAD

**Issue by saadkhan6670** [react-native-webrtc/react-native-callkeep#150]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

yes i have checked this but no luck

## Description

i have just installed your library and tried this code snippet.

![image](https://user-images.githubusercontent.com/6495045/72736461-90a8df00-3bbf-11ea-9993-4f2b89a1510b.png)

but its returning false in RNCallKeep.hasPhoneAccount.

## Versions
    - Callkeep:
    - React Native: "0.61.5"
    - iOS: latest
    - Android: latest
    - Phone model: all phones

**Comment by manuquentin** [comment]
Hi @saadkhan6670, with what kind of phone are you testing this code ? 
Have you a SIM card on this phone ? Can you provide more logs ?
Thanks

**Comment by manuquentin** [comment]
Closed due to inactivity.
Please reopen the issue with some logs if you still reproduce it.
