### ISSUE TITLE
Facing the Issue With Reject Call On IOS 13 In Background Mode As App Is Crashing 

### ISSUE THREAD

**Issue by Chaitanya-Suryadevara** [react-native-webrtc/react-native-callkeep#156]
# Bug report
When Rejecting the Call On IOS 

- Reproduced on:
 - [ ] iOS 13

## Description
When I get An Incoming VOIP Notification on IOS devices when App Is in Background mode, App Is Crashed Every time When I Reject the Notification. But Works Fine On Accept Call.
And Working Fine On Foreground Mode For Both Accept and reject.

## Steps to Reproduce
reject an Incoming call when app is in background

## Versions
    - Callkeep:3.0.9
    - React Native: 0.58.6
    - iOS:13.3.1
    - Phone model: All

## Logs  Xcode Log

2020-02-13 12:12:19.305827-0500 555 Phone RN[3791:1852152] Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.
2020-02-13 12:12:19.307019-0500 555 Phone RN[3791:1852152] *** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-37/PKPushRegistry.m:343
2020-02-13 12:12:19.307351-0500 555 Phone RN[3791:1852152] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'
*** First throw call stack:
(0x18463d80c 0x184365fa4 0x18453fc4c 0x1849756f4 0x19831ba5c 0x10241ebd8 0x10242d858 0x19831a9cc 0x10241d7fc 0x10241ebd8 0x10242cc34 0x1845bb3a8 0x1845b639c 0x1845b58a0 0x18e50d328 0x1886a6740 0x100646844 0x184440360)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by manuquentin** [comment]
Hi !
The issue `Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback` means that you have to display the incoming call screen from callkeep directly when you receive an VOIP push.

Have you added [these lines](https://github.com/react-native-webrtc/react-native-callkeep#pushkit) from the doc ?

**Comment by Chaitanya-Suryadevara** [comment]
Thank You For the Quick Response I have added the Lines In Appdelegate.m
File
Please refer This Added File
I am Not Sure Why This Is Happening When Only Rejecting the Call

-(*void*)pushRegistry:(PKPushRegistry *)registry
didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(
PKPushType)type withCompletionHandler:(*void* (^)(*void*))completion

{

  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload
forType:(NSString *)type];

  NSString *strDict = [payload.dictionaryPayload objectForKey:@"user_data"];

  NSData *data = [strDict dataUsingEncoding:NSUTF8StringEncoding];

  NSDictionary *jsonDict = [NSJSONSerialization JSONObjectWithData:data
options:0 error:*nil*];

  NSString *callerName = [jsonDict valueForKeyPath:@"data.cname"];

  NSString *notiType = [payload.dictionaryPayload valueForKeyPath:@"type"];

  NSString *uuidNew = [[[NSUUID UUID] UUIDString] lowercaseString];

  NSString *handle = [jsonDict valueForKeyPath:@"data.cid"];

  //  NSString *uuid = [jsonDict valueForKeyPath:@
"notification.extTrackingID"];

  NSLog(@"didReceiveIncomingPushWithPayload=%@=%@=%@=%@", uuidNew, handle,
callerName, notiType);

  *if* ([notiType isEqualToString:@"notify"]){

    [RNCallKeep reportNewIncomingCall:uuidNew handle:handle handleType:
@"number" hasVideo:*false* localizedCallerName:callerName fromPushKit:*YES*
];

    completion();

  }

}

**Comment by manuquentin** [comment]
I don't really understand, since you added these lines, do you still have the `Killing app because it never posted an incoming call` error ?

What's the error when you reject you call ?

**Comment by Chaitanya-Suryadevara** [comment]
Hi Emmanuel,
I am getting this Exception and an Error From Xcode Log,

*2020-02-10 16:32:35.163972-0500 555 Phone RN[2217:708351] Apps receving
VoIP pushes must post an incoming call (via CallKit or
IncomingCallNotifications) in the same run loop as
pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:]
without delay.*

*2020-02-10 16:32:35.164054-0500 555 Phone RN[2217:708351] *** Assertion
failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes],
/BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-37/PKPushRegistry.m:343*

*2020-02-10 16:32:35.164313-0500 555 Phone RN[2217:708351] *** Terminating
app due to uncaught exception 'NSInternalInconsistencyException', reason:
'Killing app because it never posted an incoming call to the system after
receiving a PushKit VoIP push callback.'*

**** First throw call stack:*

*(0x1adb4ea48 0x1ad875fa4 0x1ada50e88 0x1ade86654 0x1c1892a5c 0x1047a2bd8
0x1047b1858 0x1c18919cc 0x1047a17fc 0x1047a2bd8 0x1047b0c34 0x1adacc5e4
0x1adac75d8 0x1adac6adc 0x1b7a67328 0x1b1bd463c 0x10296e024 0x1ad950360)*

*libc++abi.dylib: terminating with uncaught exception of type NSException*

**Comment by rcidt** [comment]
I also see this error `_terminateAppIfThereAreUnhandledVoipPushes` in crash logs in production.

As far as I know, I have implemented CallKeep just as the README states. I am wondering if CallKeep is getting hung up somewhere between the time the VoIP Push arrives and it displays the CallKit UI.

**Comment by Chaitanya-Suryadevara** [comment]
@rcidt  Can You Explain Me How You Solve This Issue ?
This Issue is Happening Only When The User Rejects the Call and Not When the Remote User Disconnects the Call

**Comment by manuquentin** [comment]
Hi @Chaitanya-Suryadevara by using the code in the README, you have to report the call as soon as possible to iOS. That's why iOS aborts the call.

Did the `reportNewIncomingCall:uuidNew ` is called in the Objective-C code ?

**Comment by Chaitanya-Suryadevara** [comment]
Hi React-Native-Webrtc/React-Native-Callkeep
*Yes the* reportNewIncomingCall:uuidNew *is called when incoming call is
displayed *
*The Issue is Only with the Reject call (when I reject the Notification
When app is in background).*
*Basically Our Server Gives Two VOIP Push Notifications One for Notify and
the other for Cancel.*
*For Notify I am Directly reporting to CallKit but when user rejects the
call a cancel VOIP is Coming Do I need to handle this cancel VOIP also In
the native Code ?*
*I am Handling the Cancel VOIP In JS code can You Explain Please *

*Thanks,*
*Please Find the sample of the Notification Attached.*

*Notify:*
VOIP PUSH NOTIFICATION (DASHBOARD SCREEN) =>
 {"_data":{"room_token":"ce8a96768193781899f1d58c561938e06484fa90","routing_id":"
c075cf00-dbe4-11e9-9aad-fa163ef745f7@uc-prod.comcast.com","rtc_server":"
pr-xmpp-as-a-004.555.comcast.com
","room_id":"3gpode18an-c075cf00-dbe4-11e9-9aad-fa163ef745f7","type":"notify","user_data":"{\"data\":{\"cid\":\"+19999999999\",\"cname\":\"SAMPLE\"},\"notification\":{\"callID\":\"
BW0329572041103201378410112-1348510362@10.22.99.196
\",\"extTrackingID\":\"eae8a21a-a914-4e36-a8c0-f9052e22dc3a\",\"topic\":\"federation/pstn\",\"type\":\"pstn\",\"verstat\":\"\"}}","trace_id":"
BW0329572041103201378410112-1348510362@10.22.99.196","room_token_expiry_time":1583897577},"_alert":"Incoming
call...","_sound":"default","_badgeCount":1}
9264f58a-cd5f-4cb4-8…c3d478afa70a:183509 PUSH NOTIFICATION TYPE (DASHBOARD
SCREEN) =>  notify

*Cancel:*
VOIP PUSH NOTIFICATION (DASHBOARD SCREEN) =>  {"_data":{"routing_id":"
c075cf00-dbe4-11e9-9aad-fa163ef745f7@uc-prod.comcast.com
","room_id":"3gpode18an-c075cf00-dbe4-11e9-9aad-fa163ef745f7","type":"cancel","trigger":"canceled","trace_id":"
BW0329572041103201378410112-1348510362@10.22.99.196
","user_data":"{\"data\":{\"cid\":\"+19999999999\",\"cname\":\"SAMPLE\"},\"notification\":{\"callID\":\"
BW0329572041103201378410112-1348510362@10.22.99.196
\",\"extTrackingID\":\"eae8a21a-a914-4e36-a8c0-f9052e22dc3a\",\"topic\":\"federation/pstn\",\"type\":\"pstn\",\"verstat\":\"\"}}"},"_sound":"default","_badgeCount":1}
9264f58a-cd5f-4cb4-8…c3d478afa70a:183509 PUSH NOTIFICATION TYPE (DASHBOARD
SCREEN) =>  cancel

**Comment by zxcpoiu** [comment]
@Chaitanya-Suryadevara 

It is because you only `reportNewIncomingCall`by condition where `type = "notify"`
But you send the second `VoIP Push` which has `type = "cancel"`, so it never go into `reportNewIncomingCall` block.
 
Apple forced us to invoke `reportNewIncomingCall` each time when you receive any single one Voip Push, and ASAP. Or the app will crash. ( even if you had currently displayed CallKit Incoming Call View, it doesn't count. )

Every VoIP PUSH should invoke `reportNewIncomingCall` once.
On iOS 13. VoIP push now does one and only one thing, is to let you invoke `reportNewIncomingCall`, nothing else. 

### suggestion:

Use `remote notification` to send `cancel` silent push instead use voip push.
Although according to doc, it's priority may be lower (5 instead 10) and not guarantee to arrive in the first time. But since your device is waked, so it should be arrive in time.

It's the suggestion from the staff of Apple I saw in a discussion.

```
  *if* ([notiType isEqualToString:@"notify"]){

    [RNCallKeep reportNewIncomingCall:uuidNew handle:handle handleType:
@"number" hasVideo:*false* localizedCallerName:callerName fromPushKit:*YES*
];
```

**Comment by Chaitanya-Suryadevara** [comment]
Hi, Thank You for the quick response,
I am Invoking the  reportNewIncomingCall with the condition type notify and
I am Able to get the Incoming notification in background mode then accept
is working fine.
But my issue is with the reject when the app is in background mode,
So I have a Question Here Do I need to Send the Cancel VOIP also with a
condition type cancel and report to Call Kit ? In the native code ?
Because I am Already Handling the cancel in JS code But not reporting to
callkit.

**Comment by zxcpoiu** [comment]
I think I already answered your qiestion above, use remote push instead of
voip push.

If you want to use voip push, you have to , should, must, to invoke
reportNewIncomingCall for each push, that's the rule from Apple, or your
app will crash.

There is nothing we can do.

People are forced to refactor and change the whole call handling logics, no
matter how beautiful the handling process they already have.



Chaitanya Suryadevara <notifications@github.com> 於 2020年3月12日 週四 02:53 寫道：

> Hi, Thank You for the quick response,
> I am Invoking the reportNewIncomingCall with the condition type notify and
> I am Able to get the Incoming notification in background mode then accept
> is working fine.
> But my issue is with the reject when the app is in background mode,
> So I have a Question Here Do I need to Send the Cancel VOIP also with a
> condition type cancel and report to Call Kit ? In the native code ?
> Because I am Already Handling the cancel in JS code But not reporting to
> callkit.
>

**Comment by zxcpoiu** [comment]
I bet there might be somewhere triggered sending `cancel` with voip push in your code. The easiest way to try is sending `cancel` using another APN push called `remote notification`.

And you can read the newly updated Readme on RnVoipPush for related info.

https://github.com/react-native-webrtc/react-native-voip-push-notification/blob/master/README.md#important-note

**Comment by Chaitanya-Suryadevara** [comment]
Thank You Once again for your time !
That VOIP Push Coming from our Backend Server So How can Proceed in this
scenario with a silent push to the app ?
If You have any Idea Can You Explain ?

**Comment by zxcpoiu** [comment]
Yes, just change your back-end.
Use remote push instead voip push, then try. This might be the simplest try.

**Comment by Chaitanya-Suryadevara** [comment]
Thank You So Much for Your Help !

**Comment by manuquentin** [comment]
@Chaitanya-Suryadevara can you close the issue if it's ok for you ?

**Comment by Chaitanya-Suryadevara** [comment]
Can You Give me Some Time to solve this Issue
and Will Close this issue ASAP

Thanks & Regards

**Comment by manuquentin** [comment]
@Chaitanya-Suryadevara can we close this issue now ?
