### ISSUE TITLE
iOS - No known class for method selector

### ISSUE THREAD

**Issue by danwhite-ipc** [react-native-webrtc/react-native-callkeep#183]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [ ] iOS

## Description
No known class method for selector 'reportNewIncomingCall:handle:handleType:hasVideo:localizedCallerName:fromPushKit:'

I know it is probably something I have missed, but I have followed steps in documentation.

## Steps to Reproduce
Installed via Pods on new project create by RN-Cli

## Versions
    - Callkeep: 3.0.12
    - React Native: 0.62.2
    - iOS: 13.3

**Comment by danwhite-ipc** [comment]
Works fine with v3.0.10

**Comment by Punit-Vajpeyi** [comment]
I am facing the same issue.

**Comment by datht-gh** [comment]
Yeah,  i resolved problem with include extra payload to this method:
` [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES payload:nil];`

Im my case **payload** is **nil** .
Document for this: https://github.com/react-native-webrtc/react-native-callkeep#pushkit

**Comment by tuannvitt** [comment]
I am facing the same issue.

**Comment by vjhameed** [comment]
same issue here

**Comment by newme616** [comment]
same issue here

**Comment by pantomath91** [comment]
same issue here

**Comment by pantomath91** [comment]
same issue here

**Comment by thanhpk** [comment]
This might help 
https://github.com/react-native-webrtc/react-native-callkeep/issues/451#issuecomment-873182611

It should be

```
[RNCallKeep reportNewIncomingCall: uuid
                             handle: handle
                         handleType: @"generic"
                           hasVideo: NO
                localizedCallerName: callerName
                    supportsHolding: YES
                       supportsDTMF: YES
                   supportsGrouping: YES
                 supportsUngrouping: YES
                        fromPushKit: YES
                            payload: extra
              withCompletionHandler: completion];
```

instead of:

```
[RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES payload:nil];
 ```
