### ISSUE TITLE
JSON value '0' of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by Punit-Vajpeyi** [react-native-webrtc/react-native-callkeep#184]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] iOS

## Steps to Reproduce

const uuid = '0731961b-415b-44f3-a960-dd94ef3372fc';
      const handle = 'testemail@email.com';
      const localizedCallerName = 'testNickname';
      const handleType = 'email';
      const hasVideo = false;
      RNCallKeep.displayIncomingCall(
        uuid,
        handle,
        handleType,
        hasVideo,
        localizedCallerName,
      );

## Versions
    - Callkeep: 3.0.12
    - React Native: 0.62.2
    - iOS: 13.4
    - Phone model: iphone 7

## Logs

```
Paste here
```

**Comment by CaptainJeff** [comment]
Its expecting a number and is getting a string instead. The only guess i have without doing much research is either handleType or hasVideo (false could be gettin converted to a string value of 0)
