### ISSUE TITLE
Wazos Server is mandatory to integrate react-native-callkeep on the app?

### ISSUE THREAD

**Issue by pavanMude** [react-native-webrtc/react-native-callkeep#196]
So Sorry to ask this boredom questions:

I was amused to see the combination of react-native-callkeep with react-native-webrtc and how it display UI on incoming calls. I have couple of questions to ask, can someone help me out with my questions. 

1. After Looking at the Wazo-demo code and example project, I was wondering that using wazos api, server is mandatory to integrate the same in our apps!? 

2. Is phone number is necessary params to display incoming call UI!? Cant we display the UI without phone number?

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

RN Version : 0.59.9
react-native-webrtc : 1.67.1
RNCallKeep : 3.0.12

**Comment by sboily** [comment]
Hello, nope wazo is not mandatory to use callkeep, this is only an example.

**Comment by pavanMude** [comment]
Thanks for turning back @sboily, There is a parameter for phone number that should be passed to displayincomingcall() to show UI, should we provide it or we can simply neglect it!?

**Comment by sboily** [comment]
Have you check the doc on the README?

`RNCallKeep.displayIncomingCall(uuid, handle, localizedCallerName);
`
Handle is the phone number.

**Comment by pavanMude** [comment]
Yea The handle is a phone number, Is this a mandatory param to pass ?!

**Comment by manuquentin** [comment]
Yes @pavanMude the handle is mandatory for now as this library allow to display incoming calls.
We're dealing with a [non number here](https://github.com/react-native-webrtc/react-native-callkeep/compare/master...nimbleape:allow-non-numbers-and-android-video).
