### ISSUE TITLE
performAnswerCallAction and performEndCallAction not being triggered when answering/reject call from call kit

### ISSUE THREAD

**Issue by archilo20** [react-native-webrtc/react-native-callkeep#204]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [13.3.1 ] iOS

## Description
Hi I'm  able to display the incoming call screen with pushkit but as soon as I select an action  in Callkit screen, wether it is accept or decline, nothing happens and performAnswerCallAction and performEndCallAction methods in RNCallKeep.m  don't get triggered at all.

## Steps to Reproduce

- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  
  NSLog(@"VOIP received");
 
  NSUserDefaults *defaults = [[NSUserDefaults alloc] initWithSuiteName:@"NativeStorage"];
 dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
          NSLog(@"VOIP posted to RN");
         [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
       });
     
     [RNCallKeep reportNewIncomingCall:uuid handle:handle handleType:@"generic" hasVideo:false localizedCallerName:callerName fromPushKit: YES payload:nil withCompletionHandler:nil];

}

// CallKeepService.js
export default class CallKeepService {
  static instance;
init() {
    
    let options = {
      appName: properties.displayName,
      imageName: "callAppIcon",
      ringtoneSound: "my_ringtone"
    };
    try {
      RNCallKeep.setup(options);
    } catch (err) {
      console.log("error:", err.message);
    }

    // Add RNCallKeep Events
    RNCallKeep.addEventListener(
      "didReceiveStartCallAction",
      this.onRNCallKeepDidReceiveStartCallAction
    );
   
    RNCallKeep.addEventListener(
      "answerCall",
      this.onRNCallKeepPerformAnswerCallAction
    
    );
    RNCallKeep.addEventListener("endCall", this.onRNCallKeepPerformEndCallAction);
 

    
  }
}

## Versions
    - Callkeep:3.0.13
    - React Native:0.61.5
    - iOS:13.3.1
    - Android:
    - Phone model: iphone 8

## Logs

```
Paste here
```

**Comment by archilo20** [comment]
I figure my mistake.
Thanks

**Comment by mertbuldur** [comment]
how did you solve it?

**Comment by archilo20** [comment]
Hi @mertbuldur  there was a problem in my configuration.  The 
let options = {
  appName: properties.displayName,
  imageName: "callAppIcon",
  ringtoneSound: "my_ringtone"
} 
was  not in the right format as per the example.
What issue are you having ?
