### ISSUE TITLE
DidReceiveOnStartcallAction Not working with v3.0.13 (Which was Working with v3.0.12)

### ISSUE THREAD

**Issue by Chaitanya-Suryadevara** [react-native-webrtc/react-native-callkeep#206]
# Bug report

- Reproduced on:
 - [ ] iOS

## Description
when I press the Call Logs On Native caller Screen Listener is Not Invoking ! To make an Outgoing Call.

## Steps to Reproduce
Try to Make a Outgoing Call From IOS Native call Logs (Where the Our App Call Logs are saved)

## Versions
    - Callkeep: 3.0.13
    - React Native: 0.61.4
    - iOS: 13.5
    - Phone model: 11 Pro Max

**Comment by grit96** [comment]
I'm seeing the same issue. I tried on 3.0.12 and it works fine, but I can't see any obvious reason in the diff https://github.com/react-native-webrtc/react-native-callkeep/compare/3.0.12...3.0.13

**Comment by grit96** [comment]
I narrowed it down to #171 where the default `supportedHandleTypes` was changed from `CXHandleTypePhoneNumber` to `CXHandleTypeGeneric`, breaking the start call from recents action.

I've raised a PR to fix it in #207.
