### ISSUE TITLE
Android bug call background in release apk

### ISSUE THREAD

**Issue by rph17** [react-native-webrtc/react-native-callkeep#224]
When calling the release call the app starts the call with an error in the app and ends the call.

# Bug report
- Reproduced on:
 - [X] Android
 - [ ] ion 

index.js
```

export function backgroundHandler (message: RemoteMessage) {
     const callUUID = getNewUuid();
     let number = String(Math.floor(Math.random() * 100000));
      return RNCallKeep.displayIncomingCall(callUUID, number, "teste", 'number', false);
}
  AppRegistry.registerHeadlessTask('ReactNativeFirebaseMessagingHeadlessTask', () => backgroundHandler);

```
## Logs
06-23 01:53:35.052  3717  3717 E .devicesecurit: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:35.240  3636  3693 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'u()(c).then')
06-23 01:53:35.241  3636  3693 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'u()(c).then')
06-23 01:53:35.305  3636  3694 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
06-23 01:53:35.305  3636  3694 E AndroidRuntime: Process: dr.consulta, PID: 3636
06-23 01:53:35.305  3636  3694 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'u()(c).then'), stack:
06-23 01:53:35.305  3636  3694 E AndroidRuntime: startHeadlessTask@334:2841
06-23 01:53:35.305  3636  3694 E AndroidRuntime: value@29:3685
06-23 01:53:35.305  3636  3694 E AndroidRuntime: <unknown>@29:841
06-23 01:53:35.305  3636  3694 E AndroidRuntime: value@29:2939
06-23 01:53:35.305  3636  3694 E AndroidRuntime: value@29:813
06-23 01:53:35.305  3636  3694 E AndroidRuntime: value@-1
06-23 01:53:35.305  3636  3694 E AndroidRuntime: 
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
06-23 01:53:35.305  3636  3694 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
06-23 01:53:35.402  5874 16213 E Telecom : CallScreeningServiceFilter: Unbind error: (...->CS.crCo->H.CS.crCo)->CSW.hCCC@E-E-Tjg
06-23 01:53:35.402  5874 16213 E Telecom : java.lang.IllegalArgumentException: Service not registered: com.android.server.telecom.callfiltering.CallScreeningServiceFilter$CallScreeningServiceConnection@cf62fb9
06-23 01:53:35.402  5874 16213 E Telecom :      at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1870)
06-23 01:53:35.402  5874 16213 E Telecom :      at android.app.ContextImpl.unbindService(ContextImpl.java:1848)
06-23 01:53:35.402  5874 16213 E Telecom :      at android.content.ContextWrapper.unbindService(ContextWrapper.java:755)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.callfiltering.CallScreeningServiceFilter.finishCallScreening(CallScreeningServiceFilter.java:253)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.callfiltering.CallScreeningServiceFilter.startCallScreeningFilter(CallScreeningServiceFilter.java:241)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.callfiltering.CallScreeningServiceController.bindDefaultDialerAndUserChosenService(CallScreeningServiceController.java:197)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.callfiltering.CallScreeningServiceController.bindCarrierService(CallScreeningServiceController.java:168)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.callfiltering.CallScreeningServiceController.startFilterLookup(CallScreeningServiceController.java:116)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.callfiltering.IncomingCallFilter.performFiltering(IncomingCallFilter.java:72)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.CallsManager.onSuccessfulIncomingCall(CallsManager.java:688)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.Call.handleCreateConnectionSuccess(Call.java:1831)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.CreateConnectionProcessor.handleCreateConnectionSuccess(CreateConnectionProcessor.java:488)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.ConnectionServiceWrapper.handleCreateConnectionComplete(ConnectionServiceWrapper.java:1699)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.ConnectionServiceWrapper.access$100(ConnectionServiceWrapper.java:69)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.server.telecom.ConnectionServiceWrapper$Adapter.handleCreateConnectionComplete(ConnectionServiceWrapper.java:83)
06-23 01:53:35.402  5874 16213 E Telecom :      at com.android.internal.telecom.IConnectionServiceAdapter$Stub.onTransact(IConnectionServiceAdapter.java:361)
06-23 01:53:35.402  5874 16213 E Telecom :      at android.os.Binder.execTransactInternal(Binder.java:1021)
06-23 01:53:35.402  5874 16213 E Telecom :      at android.os.Binder.execTransact(Binder.java:994)
06-23 01:53:35.416  5874  5981 E DecorView: mWindow.mActivityCurrentConfig is null
06-23 01:53:35.478  3754  3754 E Zygote  : isWhitelistProcess - Process is Whitelisted
06-23 01:53:35.479  3754  3754 E Zygote  : accessInfo : 1
06-23 01:53:35.486  5874  5981 E DecorView: mWindow.mActivityCurrentConfig is null
06-23 01:53:35.491  5378  8209 E BufferQueueProducer: [Application Error: dr.consulta#0] disconnect: not connected (req=1)
06-23 01:53:35.493  3754  3754 E ettingsprovide: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:35.599 14980 14980 E ApduServiceInfo: ###---
06-23 01:53:35.696 14980 14980 E ApduServiceInfo: ###---
06-23 01:53:35.960  5874  5986 E Watchdog: !@Sync 9587 [2020-06-23 01:53:35.960] FD count : 790, wdog_way : softdog
06-23 01:53:36.021 15443 15443 E IUHostManager: getDevicesToSend [call]
06-23 01:53:36.022 15443 15443 E IUHostManager: call is allowed for device(##:##:##:##:AF:C8)
06-23 01:53:36.031  3825  3825 E Zygote  : isWhitelistProcess - Process is Whitelisted
06-23 01:53:36.032  3825  3825 E Zygote  : accessInfo : 1
06-23 01:53:36.051  3825  3825 E ndroid.incallu: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:36.056  3838  3838 E Zygote  : isWhitelistProcess - Process is Whitelisted
06-23 01:53:36.059  3838  3838 E Zygote  : accessInfo : 1
06-23 01:53:36.069  3838  3838 E m.samsung.cran: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:36.146  3838  3838 E [Crane][TelecomAdapter]: setInCallService
06-23 01:53:36.156  5503 25673 E SEC_DRM_PLUGIN_Omafl: OmaPlugin::onOpenDecryptSession(fd)::Drm2IsDrmFileByExtFd::file is NOT DRM by extension
06-23 01:53:36.229  5350  5350 E Sensors : inject_scontext_data: New ssp_data_injection_fd(31)
06-23 01:53:36.230  3881  3881 E Zygote  : isWhitelistProcess - Process is Whitelisted
06-23 01:53:36.231  3881  3881 E Zygote  : accessInfo : 1
06-23 01:53:36.254  3881  3881 E c.hearingadjus: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:36.269  3901  3901 E Zygote  : isWhitelistProcess - Process is Whitelisted
06-23 01:53:36.270  3901  3901 E Zygote  : accessInfo : 1
06-23 01:53:36.274 15443 15443 E GearModuleS$Call$SecCallHandlerProviderUtils: rejectmsg : Envie mensagem de texto.
06-23 01:53:36.274 15443 15443 E GearModuleS$Call$SecCallHandlerProviderUtils: rejectmsg : Você pode ligar novamente mais tarde?
06-23 01:53:36.274 15443 15443 E GearModuleS$Call$SecCallHandlerProviderUtils: rejectmsg : Ligarei de volta.
06-23 01:53:36.280  3901  3901 E pmode.uiservic: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:36.305  5503 25673 E SEC_DRM_PLUGIN_Omafl: OmaPlugin::onOpenDecryptSession(fd)::Drm2IsDrmFileByExtFd::file is NOT DRM by extension
06-23 01:53:36.362  5874  8169 E SensorManager: sensor is null
06-23 01:53:36.407 16404 16404 E SDHMS:ib.qa: e = /sys/class/lcd/panel/vrr: open failed: ENOENT (No such file or directory)
06-23 01:53:36.487  3825  3825 E ActivityThread: Failed to find provider info for com.cequint.ecid
06-23 01:53:36.499  3825  3825 E SCallUI : RecordVoiceFeatureImpl - NameNotFoundException
06-23 01:53:36.499  3825  3825 E SCallUI : RecordVoiceFeatureImpl - suguden exists : false
06-23 01:53:36.519 15037 15405 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
06-23 01:53:36.526  3825  3825 E SCallUI : PackageManagerModelImpl - getApplicationInfo() failed: android.content.pm.PackageManager$NameNotFoundException: com.samsung.android.incall.contentprovider
06-23 01:53:36.556  3957  3957 E Zygote  : isWhitelistProcess - Process is Whitelisted
06-23 01:53:36.557  3957  3957 E Zygote  : accessInfo : 1
06-23 01:53:36.571  3957  3957 E id.app.contact: Not starting debugger since process cannot load the jdwp agent.
06-23 01:53:36.600 30889  3751 E BatteryFasDaoImpl: This app com.samsung.android.aremoji is disabled now, so we do not insert this app to FAS table
06-23 01:53:36.600 30889  3751 E BatteryFasDaoImpl: traverseFasDatabase : 10011 com.samsung.android.aremojiis disabled now, so we skip !!
06-23 01:53:36.620  3825  3825 E SCallUI : ScreenUtils - isOnDesktopDisplay - display is null

**Comment by manuquentin** [comment]
Hi,
As a quick reply, it could be `registerHeadlessTask` need a function that returns a Promise, which `RNCallKeep.displayIncomingCall` [doesn't](https://github.com/react-native-webrtc/react-native-callkeep/blob/e95288a28e36ebc7ec0fe60e3da8df0fc81487d2/index.js#L59).

I think you should do :
```js
export function backgroundHandler (message: RemoteMessage) {
     const callUUID = getNewUuid();
     let number = String(Math.floor(Math.random() * 100000));
     RNCallKeep.displayIncomingCall(callUUID, number, "teste", 'number', false);
     return Promise.resolve();
}
AppRegistry.registerHeadlessTask('ReactNativeFirebaseMessagingHeadlessTask', () => backgroundHandler);
```

**Comment by rph17** [comment]
@manuquentin Thanks, problem resolved!
