### ISSUE TITLE
Additional improvements in headless mode

### ISSUE THREAD

**Issue by jpudysz** [react-native-webrtc/react-native-callkeep#226]
Hello, I would like to create PR with additional improvements related to headless mode. Before I create PR please let me know if it's needed. My previous PR (#221 ) was left without any response so I'm trying to implement needed features on my fork and I can share them with community. 

But let's go back to new improvements:
I took code from @manuquentin (#223) and added a few changes:
- I left old functionality of `backToForeground`, just added improvement for silent fail in the headless mode
- I introduced a new method `openAppFromHeadlessMode` which can take `callUUID`  and saves it
- Whenever we want (especially after a cold boot) we can use another method `getExtrasFromHeadlessMode` and redirect to user's call UI

With this PR we would be able to drop additional dependency like `react-native-invoke-app`.

Demo:
```
messaging().setBackgroundMessageHandler(async notificaiton => {
    return startCallFromBackgroundAndroid(notificaiton.data, headlessMode)
})

const startCallFromBackgroundAndroid = (payload, isHeadless) => {
    // setup RNCallKeep
   // set available

   RNCallKeep.addEventListener('answerCall', ({ callUUID }) => {
      RNCallKeep.openAppFromHeadlessMode(callUUID)
  })
}

// Later eg. after navigation did mount:

useAsyncEffect(async () => {
  const extras = await RNCallKeep.getExtrasFromHeadlessMode()

  if (extras) {
     navigation.navigate(ScreenNames.CallScreen, {
         roomUUID: extras.callUUID
     })
  }

}, [])
```

**Comment by manuquentin** [comment]
Hi @jpudysz,
I'll take a look at your PR soon.
For the backToForeground, I've merged a #223 that will open the app if the activity if not started.
I don't understand the use of `openAppFromHeadlessMode`. Is it when you don't have firebase and so not access to [setBackgroundMessageHandler](https://firebase.google.com/docs/cloud-messaging/js/receive) ?

**Comment by jpudysz** [comment]
It's for the case when my Android app is killed (even with a locked screen). 

Current behaviour:
- app receives FCM push and runs the headless task
- we can display CallKeep UI, handle call etc.

With my PR:
- app receives FCM push and runs the headless task
- CallKeep UI is visible
- on `answerCall` I'm opening my app (cold boot) from the headless task and the user is redirected to my call screen UI

**Comment by maitzeth** [comment]
Hello, Im having a similar problem, but I dont know if my implementation is not good enough. 

When I receive a call Push Notification from `setBackgroundMessageHandler` I attach all the event listeners  but the app doesnt not open when I answer the IncomingCall.

I tried to install `react-native-invoke-app` but I think is deprecated, cuz doesnt work on Android 9 and 10.
 
I dont know if my problem is related to this.

**Comment by manuquentin** [comment]
Hi @maitzeth,
I think you need [backToForeground](https://github.com/react-native-webrtc/react-native-callkeep#backtoforeground) on Android to open you app.

**Comment by maitzeth** [comment]
Hello @manuquentin yes, I saw your last PR from yesterday. 

This feature was needed. Thank you!

**Comment by maitzeth** [comment]
> Hi @maitzeth,
> I think you need [backToForeground](https://github.com/react-native-webrtc/react-native-callkeep#backtoforeground) on Android to open you app.

Hello @manuquentin yes, I saw your last PR from yesterday.

This feature was needed. Thank you!

I have a little question: There is a way to open the app on `setBackgroundMessageHandler` from firebase listener instead of firing `backToForeground` on  `answerCall` listener?

**Comment by manuquentin** [comment]
Hi @maitzeth,
Yes I see no reason that `backToForeground` will not work in `setBackgroundMessageHandler`

**Comment by maitzeth** [comment]
@manuquentin I've write an issue something in Android 9 and 10 in this https://github.com/react-native-webrtc/react-native-callkeep/issues/227#issue-645603593 do you have any idea about this?

**Comment by jpudysz** [comment]
Hello everyone, I'm super busy and I can't contribute here, what's more, we are far behind each other. You can check my repo with a few additional improvements for Android (https://github.com/jpudysz/react-native-callkeep) - tested on production as I'm developing for my client's VoIP app.

I tried to create PR here, but I changed `backToForeground` logic and it differs from original repo. New functionality such as headless mode, locked screen are strictly connected with this function and I can't merge it. Ideally, we can take my ideas and merge it with the master (I don't mind and you can copy-paste my code under your PR). Ping me if I needed.

PS. I added changelog inside my repo, so you can check new functionalities.
@manuquentin if you want to discuss how to merge it or you need some explanation ping/PM me.

**Comment by nero2009** [comment]
Thank you so much @jpudysz . you fork helped me get add functionality that I really needed for my usecase

- Answer call in lock screen
- Custom call UI

Thanks alot for sharing.

**Comment by jpudysz** [comment]
I'm happy that I was able to help someone. Cheers from Poland!

**Comment by juanxog** [comment]
Thanks you so much  @jpudysz ,  very useful.  solved my problem with backforeground and answerCall event.
I have a new problem with openAppFromHeadlessMode, when i call it in setBackgroundMessageHandler of firebase with terminated state, it doesn't open my app only show (answered nativeUI) i would like to open my app and show my videocall screen.

**Comment by ch3tan03** [comment]
> Thanks you so much @jpudysz , very useful. solved my problem with backforeground and answerCall event. I have a new problem with openAppFromHeadlessMode, when i call it in setBackgroundMessageHandler of firebase with terminated state, it doesn't open my app only show (nativeUI answered) i would like to open my app and show my videocall screen. Additionally, i tried to use backForeground but the app doesn't open.

Any update on this?

**Comment by juanxog** [comment]
@ch3tan03 use this fork https://github.com/jpudysz/react-native-callkeep

**Comment by fukemy** [comment]
hi, any solution for IOS? In case app killed I can not do anything. Can someone help
