### ISSUE TITLE
CallKeep Not Keeping Call in IOS

### ISSUE THREAD

**Issue by stephanoparaskeva** [react-native-webrtc/react-native-callkeep#229]
### Env:
* IOS
* React Native 0.62.2
* CallKeep 3.0.15

### Explanation
* Outgoing Calls display *No UI*
* Incoming calls *successfully* display UI
* Accept Incoming call makes Native Call UI *go to background*

### Goal
* I want to see Native UI when making Outgoing Call
* I want to see Native UI when accepting call (Not for it to be backgrounded.)

### Steps
* Start a Call on Phone A to call Phone B
* Phone A displays nothing. Phone B displays incoming call. 
* Accept call on Phone B. Now Phone B shows nothing. Call hides in the background for Phone B.

## Example:
Phone A makes call (No UI), Phone B sees Incoming Call UI, Phone B accepts, Phone B UI disappears to background Tab.
### Phone A
> ![phonaA](https://user-images.githubusercontent.com/40718272/85831718-9ca85680-b786-11ea-8cf7-15cbca3645ea.gif)
### Phone B
![phoneB0](https://user-images.githubusercontent.com/40718272/85831725-a16d0a80-b786-11ea-9018-33412a9ae9ba.JPG)![phoneB1](https://user-images.githubusercontent.com/40718272/85831727-a16d0a80-b786-11ea-9cc1-5f9e87146056.JPG)

## Example using React-Native-Callkeep Demo

![ezgif com-optimize](https://user-images.githubusercontent.com/40718272/85902897-fc414900-b7fc-11ea-85b1-065e74952dad.gif)

**This is the same for Audio, and for Video**

## Code:
```JavaScript
  const oneTimeId = () => {
    callId.current = callId.current || uuid();
    return callId.current;
  };

  const initializeWebRtc = async () => {
    await Wazo.Phone.connect({ audio: true, video: true });

    Wazo.Phone.on(Wazo.Phone.ON_CALL_OUTGOING, (outgoingSess: any) => {
      session.current = outgoingSess;
      const { number: num } = outgoingSess;
      RNCallKeep.startCall(oneTimeId(), num, num, 'number', false);
    });
    Wazo.Phone.on(Wazo.Phone.ON_CALL_INCOMING, (incomingSess: any) => {
      session.current = incomingSess;
      const { number: num } = incomingSess;
      RNCallKeep.displayIncomingCall(oneTimeId(), num, num, 'number', false);
    });
    Wazo.Phone.on(Wazo.Phone.ON_CALL_ACCEPTED, () => {
      // @ts-ignore
      RNCallKeep.setCurrentCallActive(oneTimeId());
      if (session.current.cameraEnabled) {
        const sipSession = Wazo.Phone.getCurrentSipSession();
        const { peerConnection } = sipSession.sessionDescriptionHandler;
        localStream.current = peerConnection
          .getLocalStreams()
          .find((stream: any) => !!stream.getVideoTracks().length);
        remoteStream.current = peerConnection
          .getRemoteStreams()
          .find((stream: any) => !!stream.getVideoTracks().length);

        dispatch({
          localStreamURL: localStream.current?.toURL() ?? null,
          remoteStreamURL: remoteStream.current?.toURL() ?? null,
        });
      }
    });
    Wazo.Phone.on(Wazo.Phone.ON_CALL_FAILED, () => {
      RNCallKeep.endCall(oneTimeId());
      callId.current = '';
      dispatch({ inCall: false });
    });
    Wazo.Phone.on(Wazo.Phone.ON_CALL_ENDED, () => {
      RNCallKeep.endCall(oneTimeId());
      callId.current = '';
      onCallTerminated();
    });
  };

  const initializeCallKeep = async () => {
    try {
      RNCallKeep.setup(options);
      RNCallKeep.setAvailable(true);
      RNCallKeep.addEventListener('didReceiveStartCallAction', onCall);
      RNCallKeep.addEventListener('answerCall', onAnswerCallAction);
      RNCallKeep.addEventListener('endCall', hangup);
    } catch (err) {
      console.warn('initializeCallKeep error:', err.message);
    }
  };

  const init = async () => {
    await initializeCallKeep();
    await initializeWebRtc();
  };
```

**Comment by akshitrcrm** [comment]
same with me

**Comment by akshitrcrm** [comment]
@stephanoparaskeva I think this issue is from the native Callkit framework side. I checked other apps such as whatsApp, slack, and they have their own calling UI and the behaviour is same as we are getting from this library. Even in those apps there was no way they could show the native calling screen. So I guess it's just not possible until apple does something. Do you know any app that does that?

**Comment by MrAlexWeber** [comment]
Thanks @akshitrcrm for confirming this. I was also experiencing this behavior, so it's glad to know that this is at least _common_ if not entirely expected. 

I confirmed using Facebook Messenger that when answering a call from a CallKit screen:
* I saw the Messenger app's call screen, and
* When I used the App Switcher, I saw a CallKit 'in call' screen.
