### ISSUE TITLE
React-Native-CallKeep not working on ios 13.3.1 version

### ISSUE THREAD

**Issue by LiyaJohn21** [react-native-webrtc/react-native-callkeep#253]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] iOS

## Description
react-native-callkeep incoming call ui is not displaying when app is in background, but it works fine when app is in foreground state. Noticed that this issue was reported from iOS 13.0 or newer. 

## Versions
    - Callkeep: 3.1.1
    - React Native: 0.62.2
    - iOS: 13.3.1
    - Phone model: ipad mini 4

## Logs

```
Paste here
```

**Comment by whitmanc** [comment]
@LiyaJohn21 You have setup and configured VoIP notifications, correct? If you don't, it will not work.

**Comment by whitmanc** [comment]
As a note, we have the library working with iOS 13 - it does work with this version of iOS.

**Comment by LiyaJohn21** [comment]
closing this issue
https://stackoverflow.com/questions/58115125/ios-13-not-getting-voip-push-notifications-in-background
