### ISSUE TITLE
Is it possible? Call without SIM(phone number)

### ISSUE THREAD

**Issue by crazypioneer** [react-native-webrtc/react-native-callkeep#286]
Does this great repo needs phone number to start call?
Should I start call without phone number(handle)?
`RNCallKeep.startCall(uuid, handle, contactIdentifier);`

**Comment by mochi08** [comment]
I am wondering the same thing.  I want to integrate CallKeep for WebRTC, but if it requires a phone sim to work it's going to be a problem.  What I found so far is that in my test phone without a sim card, there doesn't seem to be a way to even grand permission on RNCallKeep.setup(), and RNCallKeep.startCall(uuid, calleePhoneNum, contactId) does not do anything.  On my phone with sim they work just fine.

**Comment by manuquentin** [comment]
Hi @crazypioneer, no you don't need a SIM card to use this library. Only the Pixel devices [requires one](https://github.com/react-native-webrtc/react-native-callkeep/issues/93) to ba able to make an outgoing call (even with Wifi).

**Comment by crazypioneer** [comment]
Thank you!!! I will check it.

**Comment by mochi08** [comment]
@manuquentin thanks, that's great news.  According to documentation, for the method RNCallKeep.startCall(uuid, handle, contactIdentifier), "handle" is the phone number of the callee, that's why I though a sim is required.  Does it have to be a phone number?  Can it be email or something else?

**Comment by HarshitPadalia** [comment]
> @manuquentin thanks, that's great news. According to documentation, for the method RNCallKeep.startCall(uuid, handle, contactIdentifier), "handle" is the phone number of the callee, that's why I though a sim is required. Does it have to be a phone number? Can it be email or something else?

yes you can also user caller name instead as I am passing caller name in place of phone number and it's working just fine

**Comment by HarshitPadalia** [comment]
> > @manuquentin thanks, that's great news. According to documentation, for the method RNCallKeep.startCall(uuid, handle, contactIdentifier), "handle" is the phone number of the callee, that's why I though a sim is required. Does it have to be a phone number? Can it be email or something else?
> 
> yes you can also user caller name instead as I am passing caller name in place of phone number and it's working just fine

if you have any solution for https://github.com/react-native-webrtc/react-native-callkeep/issues/292 then let me know

**Comment by mochi08** [comment]
> yes you can also user caller name instead as I am passing caller name in place of phone number and it's working just fine
Thanks.  One more related question, on your device without sim, do you still need to initiate with "RNCallKeep.setup" for permission before invoking other methods?  When I call "setup" for permission in my device w/o sim, if I click "ok" to accept, I don't have an option to turn on the permission so every time I restart the app it will prompt for permission again.

**Comment by HarshitPadalia** [comment]
> > yes you can also user caller name instead as I am passing caller name in place of phone number and it's working just fine
> 
> Thanks. One more related question, on your device without sim, do you still need to initiate with "RNCallKeep.setup" for permission before invoking other methods? When I call "setup" for permission in my device w/o sim, if I click "ok" to accept, I don't have an option to turn on the permission so every time I restart the app it will prompt for permission again.

I have faced same issue in one samsung device even with SIM card

**Comment by HarshitPadalia** [comment]
> > > yes you can also user caller name instead as I am passing caller name in place of phone number and it's working just fine
> > 
> > 
> > Thanks. One more related question, on your device without sim, do you still need to initiate with "RNCallKeep.setup" for permission before invoking other methods? When I call "setup" for permission in my device w/o sim, if I click "ok" to accept, I don't have an option to turn on the permission so every time I restart the app it will prompt for permission again.
> 
> I have faced same issue in one samsung device even with SIM card

I am finding solution for this issue if you have found any thing then let me know thanks!

**Comment by HarshitPadalia** [comment]
> > > > yes you can also user caller name instead as I am passing caller name in place of phone number and it's working just fine
> > > 
> > > 
> > > Thanks. One more related question, on your device without sim, do you still need to initiate with "RNCallKeep.setup" for permission before invoking other methods? When I call "setup" for permission in my device w/o sim, if I click "ok" to accept, I don't have an option to turn on the permission so every time I restart the app it will prompt for permission again.
> > 
> > 
> > I have faced same issue in one samsung device even with SIM card
> 
> I am finding solution for this issue if you have found any thing then let me know thanks!

@manuquenti @mochi08 @c960657 @crazypioneer  if you any solution regrading this bug then let me know!

**Comment by Andriiklymiuk** [comment]
@HarshitPadalia have you solved it?

**Comment by crazypioneer** [comment]
@Andriiklymiuk 
It's just UI kit.
It doesn't matter with sim.

**Comment by Andriiklymiuk** [comment]
@crazypioneer actually it does. If you use tablet and there is no sim slot, than the lib internally checks if there is phone account and if there isn't any-fails to display any call. This is android behaviour

**Comment by crazypioneer** [comment]
@Andriiklymiuk 
It works on Android.
But I didn't test it on Tablet...

**Comment by Andriiklymiuk** [comment]
@crazypioneer yes, it works on android, but if you test on Tablet with no sim slots-no calls.

**Comment by Andriiklymiuk** [comment]
Just if anyone interested and for people who will have tablets without calling accounts on android, here is my solution.
First and foremost: there are devices, that have no calling accounts and if you haven't chosen calling account/phone account on android, than callkeep will not work and try to ask you permission every app restart, which is not desirable behaviour. So, we need to check if there are any calling accounts, e.g. ` telecomManager.getCallCapablePhoneAccounts().isEmpty() ? false : true` and if call accounts empty-use other calling solution, which i use https://github.com/ajith-ab/react-native-voip-call , which complements callKeep perfectly for android devices without calling accounts
