### ISSUE TITLE
BIND_TELECOM_CONNECTION_SERVICE permission error with RNCallKeep

### ISSUE THREAD

**Issue by mochi08** [react-native-webrtc/react-native-callkeep#289]
I am trying to use RNCallKeep by testing it first.  I am getting "BIND_TELECOM_CONNECTION_SERVICE permission" error when I am trying to call RNCallKeep.setup:
`componentDidMount() {`
    `const options = {`
      `ios: {`
        `appName: 'Video Call',`
      `},`
      `android: {`
        `alertTitle: 'Permissions required',`
        `alertDescription: 'This application needs to access your phone accounts for video calls',`
        `cancelButton: 'Cancel',`
        `okButton: 'ok',`
      `},`
    `};`
    `try {`
      `RNCallKeep.setup(options);`
   ` } catch (err) {`
      `console.log(err);`
    `}`
  `}`

From googling it looks like I have to add the service to androidmanifest.  So I added the following service within "application" tag:
`<service android:name=".RNCallKeep"`
`          android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE">`
`          <intent-filter>`
`              <action android:name="android.telecom.ConnectionService" />`
`          </intent-filter>`
`      </service>`

It is still giving me the error.  I have a feeling that I am not setting the "android:name=" class value correct.  I have also tried "io.wazo.callkeep", "io.wazo.callkeep.modules.RNCallKeep", "io.wazo.callkeep.RNCallKeep", "com.mycompany.myapp.RNCallKeep", and none is working.  How did you get yours to work?  Thanks.

**Comment by hungMta** [comment]
Flow the instruction : 
`<uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE"/>
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.CALL_PHONE" />

<application>
    // ...
    <service android:name="io.wazo.callkeep.VoiceConnectionService"
        android:label="Wazo"
        android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE">
        <intent-filter>
            <action android:name="android.telecom.ConnectionService" />
        </intent-filter>
    </service>
    // ....
</application>`

**Comment by mochi08** [comment]
@hungMta thanks a bunch, resolved my issue so I can move forward another step.

**Comment by ZeeshanAhmadKhalil** [comment]
i added this but i am still getting permission issue

**Comment by mlazze** [comment]
Just found out that the android:name attribute must be set to "io.wazo.callkeep.VoiceConnectionService", do not replace "io.wazo.callkeep.VoiceConnectionService" with your own identifier :D android:label can be customized

This may be obvious to many, but we spent a few hours trying to understand why it didn't work.

**Comment by shawarmaz** [comment]
> Just found out that the android:name attribute must be set to "io.wazo.callkeep.VoiceConnectionService", do not replace "io.wazo.callkeep.VoiceConnectionService" with your own identifier :D android:label can be customized
> 
> This may be obvious to many, but we spent a few hours trying to understand why it didn't work.

might be worth mentioning this in the docs

**Comment by ibmmt** [comment]
How can I solve this issue in the Expo prebuild stage?
How can I set all this permission?

**Comment by shivanitp** [comment]
Did any one find solution for this?

**Comment by iamMAHAM** [comment]
@ibmmt you can use my plugin 

```javascript
const { withAndroidManifest } = require('@expo/config-plugins');

/**
 *
 * @param {import('expo/config').ExpoConfig} config
 * @type {import('@expo/config-plugins').ConfigPlugin}
 * @returns
 */
const plugin = (config) => {
  return withAndroidManifest(config, (config) => {
    const androidManifest = config.modResults.manifest;

    if (!androidManifest?.application) {
      androidManifest.application = [];
    }

    if (!androidManifest.application[0].service) {
      androidManifest.application[0].service = [];
    }

    androidManifest.application[0].service.push({
      $: {
        'android:name': 'io.wazo.callkeep.VoiceConnectionService',
        'android:permission':
          'android.permission.BIND_TELECOM_CONNECTION_SERVICE',
        'android:exported': 'true',
      },
      'intent-filter': [
        {
          action: [
            { $: { 'android:name': 'android.telecom.ConnectionService' } },
          ],
        },
      ],
    });

    return config;
  });
};

module.exports = plugin;
```
