### ISSUE TITLE
Can't toggle speaker when display an Incoming call.

### ISSUE THREAD

**Issue by phoenix-exp10** [react-native-webrtc/react-native-callkeep#291]
# Asking

Firstly, thank you for a great library.

I’m using this lib with webrtc, I have just test on android and I have faced an issue.
When I start a call with RNCallKeep.startCall(uuid, handle, contactIdentifier); the native phone UI displays then I can interact with End-call button, Speaker (toggle speaker), Hold call, Keypad.

But when start to display a incoming call with RNCallKeep.displayIncomingCall(uuid, handle, localizedCallerName); the native phone UI displays but I can’t interact with Speaker, Hold call, Keypad.

So if the callee want to turn on the speaker, how to archive that with this library?

Any help would be very appreciated!

## Versions
    - Callkeep: 3.1.1
    - React Native: 0.62.2
    - Android: API 28
    - Phone model: Samsung M20

**Comment by khanhduy62** [comment]
Did you solve that problem?
Could you give me any solution?

Thanks in advance

**Comment by phoenix-exp10** [comment]
First of all, it was not a bug.

You will be able to toggle the speaker icon when you call this function "answerIncomingCall".
Like this: 
`
    RNCallKeep.addEventListener('answerCall', async ({ callUUID }) => {
        RNCallKeep.answerIncomingCall("0731961b-415b-44f3-a960-dd94ef3372fc");
        // do something else
    });
`
By the way, I'm coding a calling app too, so you can reach me at skype live:.cid.b520c853af6b58b2 if you want. So we can help each other.

Peace!

**Comment by khanhduy62** [comment]
@phoenix-exp10 thank you very much, I will test it :D, I have add your skype account already 👍
