### ISSUE TITLE
[IOS] Video Button pressed event in  CallKit UI

### ISSUE THREAD

**Issue by mikeangelsilva** [react-native-webrtc/react-native-callkeep#296]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] iOS

## Description
when i pressed the video button on the CallKit UI, nothings happen.
is there any code on that event? 

## Versions
    - Callkeep:latest
    - React Native: latest
    - iOS: 13.5.1
    - Phone model: Iphone 11 Pro Max

## Logs

```
Paste here
```
![image](https://user-images.githubusercontent.com/38802880/94722334-bf4f9a00-0389-11eb-889d-bd6c7b40f057.png)

**Comment by Jerome91410** [comment]
Was the same.
my handleType is defined with "generic". To be able to start your app when the user clicks on the video button, you have to setup an option in ios object:
`handleType: 'generic',``

Was not documented but saw it into the code.

Now my app is started but didn't trigger a `startcall` event. will contine my investigation

**Comment by aevaldas** [comment]
@Jerome91410 did you find out something about this video button?

**Comment by Jerome91410** [comment]
no news sry

**Comment by Alanko5** [comment]
If you click the Video button in CallKit, the continueUserActivity event is called.

```
- (void)scene:(UIScene *)scene continueUserActivity:(NSUserActivity *)userActivity  API_AVAILABLE(ios(13.0)) {
    if ([userActivity.activityType isEqualToString:@"INStartCallIntent"]) {
        INInteraction *interaction = [userActivity interaction];
        INIntent *intent = interaction.intent;
        INStartCallIntent *startCallIntent = (INStartCallIntent *)intent;
        BOOL isVideo = startCallIntent.callCapability == INCallCapabilityVideoCall;
        ....
    }
}
```

OR

```
- (BOOL)application:(UIApplication *)application dcontinueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
    if ([userActivity.activityType isEqualToString:@"INStartCallIntent"]) {
        INInteraction *interaction = [userActivity interaction];
        INIntent *intent = interaction.intent;
        INStartCallIntent *startCallIntent = (INStartCallIntent *)intent;
        BOOL isVideo = startCallIntent.callCapability == INCallCapabilityVideoCall;
        return YES;
    }
    
    return NO;
}
```
