### ISSUE TITLE
ImageName not working (IOS)

### ISSUE THREAD

**Issue by caglardurmus** [react-native-webrtc/react-native-callkeep#320]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x ] iOS

## Description
I set the imageName but its not working.

## Steps to Reproduce
I moved image to ios folder and i set it like that.

RNCallKeep.setup({
        ios:
            {
                appName: 'Bulut Klinik',
                imageName: './ios/logo.png'
            }
    });

## Versions
    - Callkeep:3.1.4
    - React Native:0.63.3
    - iOS:14
    - Phone model: iPhone 7

**Comment by caglardurmus** [comment]
I solved it. Open ios project with xCode. Drag image to root and check the copy if need option. Give imageName:'blabla.png'.
Rebuild the project and run.

**Comment by devWaleed** [comment]
@caglardurmus does it have to be.a specific size icon? I have put the icon inside ios folder which I think is project root. I see a white square only but no actual icon

**Comment by caglardurmus** [comment]
> @caglardurmus does it have to be.a specific size icon? I have put the icon inside ios folder which I think is project root. I see a white square only but no actual icon
 
You need to use *.png with transparent background and logo must me white like this:

![callkit_logo](https://user-images.githubusercontent.com/39800322/103886864-32884b00-50f3-11eb-98d1-2f1856c830a4.png)

**Comment by caglardurmus** [comment]
> How can we do this if we handle the setup in Appdelegate.m
> 
> ```
> `  [RNCallKeep setup:@{
>     @"appName": @"moozumo",
>     @"maximumCallGroups": @3,
>     @"maximumCallsPerCallGroup": @1,
>     @"supportsVideo": @NO,
>     @"imageName": @"image_name.png"
>   }];`
>   
> ```

Like you did. Here is my code. 
Note: test.png is under ios folder.

`[RNCallKeep setup:@{
    @"appName": @"Test App",
    @"imageName": @"test.png",
    @"maximumCallGroups": @2,
    @"maximumCallsPerCallGroup": @1,
    @"supportsVideo": @YES,
    @"includesCallsInRecents": @NO,
  }];`

**Comment by hgndgn** [comment]
I added the image in "Images.xcassets" in XCode and it worked fine for me.

I am using only the name without ".png" in the setup method like 
```
RNCallKeep.setup(
  {
    ios: {
      appName: "samwin",
      supportsVideo: false,
      includesCallsInRecents: false,
      imageName: "samwin_white"
    }
  }
)
```

**Comment by Irfanwani** [comment]
None of these things work. Image is never showing in the call UI, there is always a blank circle

**Comment by Irfanwani** [comment]
Why is this not added in docs, how are we supposed to know where is the package looking for the image

**Comment by Irfanwani** [comment]
Just to clear, it doesn't need to be white, we can keep the logo white just to maintain the default theme of the call UI in iOS, but, it is not necessary to make it work. 
We need to put the image in our root of the project. Open xcode, there, our project structure goes like this:
Myproject -> MyProject -> blabla

We need to put the image in the second MyProject
