### ISSUE TITLE
CallKit doesnt start app all the time

### ISSUE THREAD

**Issue by devWaleed** [react-native-webrtc/react-native-callkeep#323]
# Bug report

- Reproduced on:
 - [-] iOS

## Description
App doesnt get started on VOIP push after notification is received.

## Steps to Reproduce
Setup call keep and voip push notification. Kill your app on iOS. Now send a VOIP push. CallKIT UI is shown, we reject the call. Now when we send VOIP again, it shows call kit ui but app doesn't get started. If I end call and check active apps, no app is shown but if i click on the app icon in apps library area of mobile, app gets started instantly no splash is shown. So I am assuming on call rejection app is not being shutdown correctly.

I can see VOIP notification is received in app because  VoipPushNotification.addEventListener('notification', callback); is invoked and it prints notification in console but no other life cycle method of app is printed in console.

## Versions
    - Callkeep: 3.1.1
    - React Native: 0.63.1
    - iOS: 13.5.1
    - Phone model: iPhone 6s Plus 

## Logs

```
Paste here
```

**Comment by sboily** [comment]
Hello, i made test on iOS 14.1 and i don't reproduce that. When i answer to the call after i reject it like you said, my app is launched and the communication is established. My iphone is the 7 model.

**Comment by devWaleed** [comment]
Don't know if something in my app is wrong but I used react-native-exit-app and looks like it fixed the issue.
