### ISSUE TITLE
Make calls using default phone call app

### ISSUE THREAD

**Issue by Jhoy1992** [react-native-webrtc/react-native-callkeep#325]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description
I'm able to make and receive calls with no problem when using the app, but when a try to make a call outside the app the phone uses the default sim account to make the call, I'm using CallKeep.setAvailable(true) on my useEffect equivalent to componentdidmount but the calls still are made using the default SIM card and not the app.

## Steps to Reproduce
Just call RNCallKeep.setup() and RNCallKeep.setAvailable(true) and try to make a call using default phone dialer app.

## Versions
    - Callkeep: 3.1.4
    - React Native: 0.63.3
    - iOS: not used
    - Android: 9
    - Phone model: Motorola G6

## Logs

```
Paste here
```

**Comment by namnm** [comment]
You need to add intent for your app https://developer.android.com/reference/android/content/Intent.html#ACTION_DIAL

RNCallKeep is only for managing call inside of your app. Registering the intent is your responsibility.

**Comment by timorss** [comment]
Any good solution?

**Comment by HalilFocic** [comment]
@namnm I am having oposite issue. I don't want to Register the SIM Card for my app. When any of my users try to use their regular call to call friends or something, it asks them if they want to use SIM or my App. Is there a way of preventing this?
