### ISSUE TITLE
isCallActive returning undefined

### ISSUE THREAD

**Issue by devWaleed** [react-native-webrtc/react-native-callkeep#332]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
- [x]  iOS

## Description
I have the following code to check if answercall was pressed early before JS context is loaded.

But in this scenario isCallActive is returning me undefined all the time. First console log is printed so i know that my method is executed but isCallActive doesnt work properly so the whole 1 second timer loop doesnt work.

## Steps to Reproduce

```
this.callAcceptanceTimer = setInterval(async () => {
        console.log('Is Call Accepted for UUID: ', uuid);

        if (await RNCallKeep.isCallActive(uuid)) {
          this._onCallAccept(uuid);
          console.log('awesome');
        }
      }, 1000);
```

## Versions
    - Callkeep: 4.0
    - React Native:  0.63.3
    - iOS: 14+

**Comment by devWaleed** [comment]
Is anyone going to support here? or is this package lost? I have cleaned my node modules and pods multiple times. Sometimes it works, sometimes it doesn't. 

This is quite unstable to be honest. I am not getting anything on didLoadWithEvents either. I don't have any way to determine if a call was accepted early.

**Comment by sboily** [comment]
Have you tried with 4.0.0 or 4.0.1?

**Comment by devWaleed** [comment]
@sboily currently i am on 4.0.1 and it doesn't work

**Comment by Stephen-HWJ** [comment]
Yes, I am  having the same issue!
