### ISSUE TITLE
The example is not work in Android 11. 

### ISSUE THREAD

**Issue by poptanai** [react-native-webrtc/react-native-callkeep#336]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [ ] iOS

## Versions
    - Callkeep:
    - React Native:
    - iOS:
    - Android:
    - Phone model: 

## Logs

```
Paste here
The screen for "Incomming Call" is not showing in Android 11. In Android 10, the example is working perfectly. Please help to fix this. By the way, your component is the best where I can find in the Internet right now.

**Comment by poptanai** [comment]
After adding the SDK 11, it works fine.

**Comment by GoncaloDuarte98** [comment]
How did you add the SDK? I am having the same problem but cant figure it out. Thanks

**Comment by JeroenVanSteijn** [comment]
@GoncaloDuarte98 @poptanai how did you fix this?

**Comment by ShooterArk** [comment]
@poptanai how did you resolve the issue? The example is compiled on sdk 28 and does not use the foreground service attribute in the manifest as well. So can you please share "How did you add the SDK" ??
