### ISSUE TITLE
answerCall event not trigger in android 11

### ISSUE THREAD

**Issue by GoncaloDuarte98** [react-native-webrtc/react-native-callkeep#341]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description
AnswerCall event is not triggered in Android 11 but works on android 10. endCall works on both devices.

## Steps to Reproduce

 RNCallKeep.addEventListener('answerCall', callKitAnswered);

Listener does not get called

## Versions
    - Callkeep: 4.01
    - React Native:0.63.3
    - iOS:
    - Android:11
    - Phone model: Xiaomi mi 10 lite 5g

## Logs

```
Paste here
```

**Comment by namnm** [comment]
May be related to this: https://github.com/react-native-webrtc/react-native-callkeep#--didloadwithevents

**Comment by mozhn** [comment]
Hello, is there any improvement on this subject?

**Comment by GoncaloDuarte98** [comment]
no. same code runs in one device but my Xiaomi doesn't work

**Comment by classiebit** [comment]
Someone, please help! 🙏  `answerCall` event is not firing in Android. When we call `displayIncomingCall` and the incoming call shows on Android, and when we press the call end button, the `endCall` event is firing, but when we press the call-accept button, it stays there on the call screen and nothing happens. And the `answerCall` event is not firing. 

Please help, we've tried all the solutions, nothing is working.

**Comment by mdovn** [comment]
Same for me, answerCall is not firing on my xiaomi poco f3 phone

**Comment by srilatha141** [comment]
able to make a call, but not able to answer incoming call on android 11 and working good on android 8, please suggest any solution for android 11

**Comment by azhararmar** [comment]
Same issue here, answerCall is not firing for Android

**Comment by hgndgn** [comment]
I am using iOS and the incoming call is shown, but when I accept the call the "answerCall" event is also not firing...

**Comment by fukemy** [comment]
any solution now?
