### ISSUE TITLE
IOS App not opening on answering call in release mode

### ISSUE THREAD

**Issue by agamsps** [react-native-webrtc/react-native-callkeep#346]
Hi Team,
I have a problem i am following from quite a few day.
My app ( on answering the call from call kit UI on iPhone ) on click, is opening the app when in debug mode but does not open app in release mode .
By debug mode i mean to say when debugger ison ( edit sceme in xcode is debug )

I will explain my scenario in more depth,

I have a screen getting called in the event of 
```
RNCallKeep.addEventListener('answerCall', ({ callUUID }) => {
// i am navigating the user to a particular screen
    });
```
In debug mode :  the app opens when i answer the call, it navigates to the screen to which i have navigated to the screen in the above event listener.
In release mode :  the app **does not** open when i answer the call, But when i manually open the app, it is already navigated to that screen, means it was already fired.

So the main issue is that the answer button is not opening the app when it is in background/ killed.

For more info : i am using voip push notification and triggering to display incoming call via native code like below : 

`- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
  
  NSLog(@"printing notification: %@", [payload dictionaryPayload]);
  NSString *uuid = [[[payload dictionaryPayload] objectForKey:@"data"] objectForKey:@"channelUniqueName"];
  NSString *callerName = [[[payload dictionaryPayload] objectForKey:@"data"] objectForKey:@"callerName"];
  NSString *handle = [[[payload dictionaryPayload] objectForKey:@"data"] objectForKey:@"callerName"];
  NSString *notitype = [[[payload dictionaryPayload] objectForKey:@"data"] objectForKey:@"notificationType" ];
  
  // --- this is optional, only required if you want to call `completion()` on the js side
  [RNVoipPushNotificationManager addCompletionHandler:uuid completionHandler:completion];

  // --- Process the received push
  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];
  
    [RNCallKeep reportNewIncomingCall: uuid
                                 handle: handle
                             handleType: @"generic"
                               hasVideo: YES
                    localizedCallerName: callerName
                        supportsHolding: YES
                           supportsDTMF: YES
                       supportsGrouping: YES
                     supportsUngrouping: YES
                            fromPushKit: YES
                                payload: uuid
                  withCompletionHandler: completion];

  // --- You should make sure to report to callkit BEFORE execute `completion()`

  
  //if (@available(iOS 14, *)) {
    completion();
  //}
  // --- You don't need to call it if you stored `completion()` and will call it on the js side.
  
}`

Any kind of help would be appreciated .

**Comment by agamsps** [comment]
I got the answer, it takes 5 seconds to load the js in release mode, 
For anyone who faces this issue in future, should add a delay in the appdelegate maybe !

**Comment by mohdmunaf** [comment]
@agamsps Could you tell me how did you solve the issue? We are also facing the same issue.
