### ISSUE TITLE
How i can set Connecting text

### ISSUE THREAD

**Issue by CMLCNL** [react-native-webrtc/react-native-callkeep#348]
![image](https://user-images.githubusercontent.com/39784911/104792541-c58a4a80-57af-11eb-90bb-85db37e153f7.jpeg)

How i can set this text.

How can I do I want to print, connectting there until the chat is ready?

Because my chat is connectting in a few seconds.

**Comment by Satsh24** [comment]
Hey @CMLCNL how did you solve this for IOS ?
