### ISSUE TITLE
Update call duration time

### ISSUE THREAD

**Issue by mikeangelsilva** [react-native-webrtc/react-native-callkeep#353]
When the user accept the call, how can i update the call duration to match the actual call time between two users?

**Comment by RuFang-21** [comment]
HI , how do you fix this ya?

**Comment by ashusingh1** [comment]
I also searching for the solution.

**Comment by artur-duchenko-omnitelecom** [comment]
RNCallKeep.addEventListener('answerCall', async ({ callUUID }) => {
    console.log('answerCall', callUUID);

    //Accept call with your SIP client

   //Need to call setCurrentCallActive for duration timer start working (only for android)

    setTimeout(() => {
      RNCallKeep.setCurrentCallActive(callUUID);
    }, 1500);
  });
