### ISSUE TITLE
error: 'camera|microphone' is incompatible with attribute foregroundServiceType 

### ISSUE THREAD

**Issue by mg4u** [react-native-webrtc/react-native-callkeep#358]
# Bug report

-  I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 -  Android
 - [ ] iOS

## Description
I got this error `error: 'camera|microphone' is incompatible with attribute foregroundServiceType ` although this value is mentioned in the documentation

## Versions
    - Callkeep:^4.0.1
    - React Native: 0.63
    - iOS:
    - Android:  Compliesdk: 29
    - Phone model: 

## Logs

```
AAPT: error: 'camera|microphone' is incompatible with attribute foregroundServiceType (attr) flags [connectedDevice=16, dataSync=1, location=8, mediaPlayback=2, mediaProjection=32, phoneCall=4].

```

**Comment by grit96** [comment]
This is solved by #357

**Comment by grit96** [comment]
Setting `compileSdkVersion` to 30 in `build.gradle` will solve your issue.

**Comment by subiyantoro** [comment]
I already set my compileSdkVersion to 30 but i still got same error, can anyone help me?

**Comment by Hao4Chen** [comment]
![image](https://user-images.githubusercontent.com/18045242/109377776-7e43bd80-7908-11eb-9b7d-37e4d11ce277.png)
