### ISSUE TITLE
EndCall method should be case insensitive

### ISSUE THREAD

**Issue by Jerome91410** [react-native-webrtc/react-native-callkeep#367]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description
You can add an incoming call based on a uuid in lower case, the native code will convert it automatically in `NSUUID`.
If you want to end this call, you have to `endCall` with the uuid in upper case.

## Steps to Reproduce

on iphone Xr
create a room with a valid uuid in lowercase
try to end this call with the generated uuid.

not reproduced on iphone 8.

## Versions
    - Callkeep: 4.0.1
    - React Native: 0.61.5
    - iOS: 14.4
    - Android:
    - Phone model: 

## Logs

```
none
```

**Comment by Jerome91410** [comment]
Not reproduced on simu XR 14.4. Will investigate and reopen it if confirmed

**Comment by Jerome91410** [comment]
@namnm Hello

I do not reproduce the issue anymore. I modified the way I call endCall with a toUpperCase in case of IOS.

I closed the issue because my modification on js side seems to fix the behavior and no time for the moment to invesgate more deeply.

**Comment by Jerome91410** [comment]
@namnm To go deeper, maybe you can fetch the current calls on ios => getCalls() method.
It is just merged not released for the moment
https://github.com/react-native-webrtc/react-native-callkeep#getcalls

**Comment by Jerome91410** [comment]
@namnm reproduced the problem, test with the PR updated
https://github.com/react-native-webrtc/react-native-callkeep/pull/365/commits/eccb61ca1e770325e310b26606e29dd3fecec29d

**Comment by namnm** [comment]
@Jerome91410 how is your PR supposed to fix the issue by avoid request initcallkitprovider?
Also I can see you introduced previousSettingsStored, but couldnt find where we store the data from the first place?

**Comment by namnm** [comment]
I tried to end the call desperately using even endCall and endAllCalls, but the issue still happens sometimes. I added the log to make sure `endAllCalls` is called (but I only look at the log of react native js, couldnt have time to take a look at the native ios log yet).

**Comment by Jerome91410** [comment]
What i undestood, the steps when you receive a voip push notif with my PR of course:
- app initialized
- native part call `initCallKitProvider`
- incomingCall is called, then the native ui is displayed
- js is launched, and `RNCallKeep.setup` should be executed, the `CallKitProvider` is reinitialized.
- after this setup, it s impossible to `endCall` the call created previously. 

What the commit did : when you call `RNCallKeep.setup` it will reinitialized `CallKitProvider` only if the settings changed.

**Comment by namnm** [comment]
Even though I think the settings may always change. 
- native part call initCallKitProvider -> here we dont know which settings we provided, may be empty default
- js is launched, and RNCallKeep.setup should be executed, the CallKitProvider is reinitialized. -> here the new settings is not the default one, and it will reinitialize anyway?

**Comment by Jerome91410** [comment]
The first launch of the app, the settings stored will be empty. After js launched and `RNCallKeep.setup`with options, the settings will be stored and applied.

On the second launch, previous settings will be applied . On JS side `RNCallKeep.setup`  should be called with the same options, the callkitprovider will not be reinitialized

**Comment by Jerome91410** [comment]
i sent you a slack notif to be able to exchange easily
