### ISSUE TITLE
[Android] No audio when starting app from killed stated

### ISSUE THREAD

**Issue by JeroenVanSteijn** [react-native-webrtc/react-native-callkeep#396]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description

When I initiate the app with a silent push notification through firebase, the onnotifications starts my webrtc connection and it receives an incoming call. When I accept this call, this goes through but there is no audio. When I do the same but from background or active state all is fine.

I suspect that I can not use any audio (both microphone and speaker) when coming from a killed state. How do I resolve this?

I have foreground service implemented and I reproduced it on Samsung A50, Android 10.

I also tried backToForeground but this does not work from killed state.

## Steps to Reproduce

1. receive silent notification in killed state
2. call displayIncomingCall
3. accept and start the call
4. see that there is no audio

## Versions
    - Callkeep: 4.1.0
    - React Native: 0.63.0
    - iOS:
    - Android: 10
    - Phone model: Samsung A50

**Comment by JeroenVanSteijn** [comment]
It looks like maybe it's not a problem with the audio but a problem with the "answerCall" listener not being called because it was not registered since there is no React context.

**Comment by JeroenVanSteijn** [comment]
Yes this was the case. The listener was in App.tsx but that is never loaded in headless. Solution is to register the listener in the index.js

**Comment by fukemy** [comment]
Hi, i have the problem, that is in case app killed, i navigate to call screen when answer call, but it's does nothing. Other case work fine. Can u help? I am stucking in few days. Please

**Comment by fukemy** [comment]
i got same problem but with ios
