### ISSUE TITLE
No audio when holding old regular call and accepting new incomingcall

### ISSUE THREAD

**Issue by JeroenVanSteijn** [react-native-webrtc/react-native-callkeep#399]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [x] iOS

## Description

No audio when answering whilst in another call. On both platforms this seems to be the case. When I hold the call and then un-hold the call it is resolved, which gives me the idea that the phone does not recognize that the call or app is active.

## Steps to Reproduce

1. Call with a regular phone to the phone with the app
2. Accept the regular call on the phone with the app
3. Call to the app
4. Click on the phone with the app on 'hold current call and accept incoming call'.
5. Observe that there is no audio coming out of the app.

## Versions
    - Callkeep: 4.1.0
    - React Native: 0.63.3
    - iOS: 14
    - Android: 10
    - Phone model: Samsung A50

**Comment by JeroenVanSteijn** [comment]
Seems that it is fixed by first setting the call active in callkeep, and then start the webrtc connection, instead of the other way around

**Comment by rcidt** [comment]
Hi @JeroenVanSteijn , I am experiencing the same issue on iOS using CallKeep, RNWebRTC, and JsSIP.

I would greatly appreciate it if you could elaborate a bit more on your solution.

Thanks
