### ISSUE TITLE
Android 11 connection service not opening on displayIncomingCall or startCall

### ISSUE THREAD

**Issue by JeroenVanSteijn** [react-native-webrtc/react-native-callkeep#401]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description

On Android 11 (Samsung S10) the Connection Service does not pop up.

targetSdkVersion is set to 29

## Steps to Reproduce

1. Install on Android 11
2. Call displayIncomingCall
3. See that ConnectionService does not appear at all.

## Versions
    - Callkeep: 4.1.0
    - React Native: 0.63.0
    - iOS: x
    - Android: 11
    - Phone model: Samsung S10

**Comment by ShooterArk** [comment]
Any luck in resolving this issue?

**Comment by nero2009** [comment]
Please I am facing the same issue. Connection service UI doesn't show on Android 11 but it does on Android 9.  How were you able to resolve this @JeroenVanSteijn

**Comment by nero2009** [comment]
I had to set my `foregroundServiceType ="camera|microphone|phoneCall` in other to get it to work on Android 11(Samsung S20 ultra) and Android <11
