### ISSUE TITLE
[iOS] incoming call not showing up

### ISSUE THREAD

**Issue by er1cAk** [react-native-webrtc/react-native-callkeep#402]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description

I trying to get incoming call UI show up in iOS but unsuccessful. Only green icon in left upper corner came up for 1 sec [see video](https://drive.google.com/file/d/11cK7_3Tvwo32MzOss6scmDKW_mf2nDBx/view?usp=sharing). I followed instructions menoited in [iOS doc](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/docs/ios-installation.md).

On android notification about the call pops up but I am not able to display screen which I can see in the README.

## Steps to Reproduce
```
yarn add react-native-callkeep
yarn add react-native-uuid
cd ios && pod install --repo-update
```

folowed instructions in [iOS common setup](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/docs/ios-installation.md#common-installation-steps)

[screenshots of made changes](https://drive.google.com/drive/folders/1yIyo9R47f06VHzFu1ZCaeYU9Lbq2OePW?usp=sharing) 

in source code of app initialize RNCallKeep like is described in [setup](https://github.com/react-native-webrtc/react-native-callkeep#setup) (copy&paste)

[gist of App.tsx](https://gist.github.com/er1cAk/db22209cb4433ff49162c4f5d17f37e1)

## Versions
    - Callkeep: 4.1.0
    - React Native: 0.64.0
    - iOS: 14.4
    - Android: 8.1 (API 27)
    - Phone model: Pixel 2

## Logs

```
2021-04-24 10:15:33.729189+0200 go[68245:69240394] [RNCallKeep][reportNewIncomingCall] uuidString = f9a7240f-11be-48e4-a212-f2f098c5158b
2021-04-24 10:15:33.829550+0200 go[68245:69239173] [RNCallKeep][CXProviderDelegate][provider:performEndCallAction]
```

**Comment by Jhoy1992** [comment]
Same problem here on iOS.

**Comment by er1cAk** [comment]
[Not bug] not working only on simulator. After deploy to real device it's working properly. It will be greate to have some notice in README :) Thanks for your tredemious work
