### ISSUE TITLE
Is READ_CALL_LOG permission needed when using selfManagedMode?

### ISSUE THREAD

**Issue by aguedob** [react-native-webrtc/react-native-callkeep#408]
Google play store is rejecting me my app because I haven't requested READ_CALL_LOG permission. Is it required when using selfManagedMode? Calls are not currently registered anymore in the calls log.

**Comment by MusabBasheer** [comment]
These permissions are required as per: https://developer.android.com/guide/topics/connectivity/telecom/selfManaged#manifest

**Comment by namnm** [comment]
In our case, Google Play rejected us I guess because of we have READ_CALL_LOG permission.

The error message is like:

> Unable to verify core functionality of app
> When you submitted your app, you specified your app's core functionality as follows: Default Phone handler (and any other core functionality usage while default handler). However, we couldn’t find evidence that the app offers the declared core functionality during our review. Please submit an updated Permissions Declaration Form that includes instructions on how to verify your declared functionality, and include details such as test account information. If portions of your app are restricted, please share a link to a video of your app to help us verify the core functionalities you’ve declared.
> 
> No default handler capability
> Default handler capability for Default Phone handler (and any other core functionality usage while default handler) was listed on your declaration form, but your app does not appear to have default handler capability. Please submit a revised Permissions Declaration Form and/or add default handler capability to your app.

As I do more research, people say that this issue related to restricted permission listed here: https://support.google.com/googleplay/android-developer/answer/9888170

Im trying to remove this permission and see if it's working.

Any idea?

**Comment by MateWW** [comment]
@namnm Is it working for you after removing that permission?

**Comment by namnm** [comment]
@MateWW I have been testing it, so far no issue. After remove it, the app is approved on Play Store!

**Comment by manuquentin** [comment]
Thanks everyone.
I'm closing as the issues is resolved.

**Comment by namnm** [comment]
Why is this resolved? We need to manually remove `READ_CALL_LOG` from the code using our custom fork.

**Comment by jonastelzio** [comment]
> @jonastelzio what do you think ? Should we use `additionalPermissions` to let everyone add `READ_CALL_LOG` instead of hardcoding it ?

Yeah I'm all for removing it. As far as I know (?) if needed it could be added to the implementing apps manifest?

Now additionalPermissions is completely bypassed in self managed mode I believe, but can't the implementing app just request that permission if need be?

**Comment by agam-colaburate** [comment]
When are we going forward with removing this as we have to manually remove this.
Got my rejection today.

**Comment by se1exin** [comment]
For those that are getting rejected due to the permission (as my app did), adding the following to your `AndroidManifest.xml` removes the permission without needing to fork the repo or otherwise:

```
 <uses-permission android:name="android.permission.READ_CALL_LOG" tools:node="remove" />
```

I think this should be added to the project readme, perhaps even as an 'upgrading from version < 4.2?` warning, as my rejection was after I updated my dependencies and had no idea this new permission was added to my manifest.

**Comment by namnm** [comment]
@se1exin Very helpful solution. We are just js junky and have no idea about those android things. Thanks for the info.

**Comment by nero2009** [comment]
Dont forget to add `xmlns:tools="http://schemas.android.com/tools"` to your root manifest if you use @se1exin answer above
https://stackoverflow.com/a/31616472

**Comment by SnowLew** [comment]
> For those that are getting rejected due to the permission (as my app did), adding the following to your `AndroidManifest.xml` removes the permission without needing to fork the repo or otherwise:
> 
> ```
>  <uses-permission android:name="android.permission.READ_CALL_LOG" tools:node="remove" />
> ```
> 
> I think this should be added to the project readme, perhaps even as an 'upgrading from version < 4.2?` warning, as my rejection was after I updated my dependencies and had no idea this new permission was added to my manifest.

Thanks man

**Comment by akshaya-rao-s** [comment]
is there any example code to implement selfmanaged mode?

**Comment by namnm** [comment]
@akshaya-rao-s To implement selfmanaged, you need to:
- Write a native java android activity which contains the custom incoming call UI you want
- Write a java android react native module, which export some methods from java to be able to call from your js code. Assume the method is like `YourModule.displayCustomIncomingCallUI(...)`
- In js code, when you get the notification, you should handle as following
  - Call `RNCallKeep.displayIncomingCall(...)`
  - In your event listener `showIncomingCallUi` you call `YourModule.displayCustomIncomingCallUI(...)`
- Now your custom UI showup, you can add listener in that custom UI (in java code) then emit the event back to js code using `RCTDeviceEventEmitter`

I have full working code here (app in production using) but our implementation is a bit different https://github.com/brekekesoftware/brekekephone/blob/master/android/app/src/main/java/com/brekeke/phonedev/BrekekeModule.java#L183

**Comment by junaiddarajat** [comment]
Is this needed for the foreground service sticky notification? I'm utilizing "selfManaged: true"; I still see the sticky, I assumed that it was related to it as well. Anyone got any ideas? App got rejected; docs state to use that flag we need that permission.

**Comment by dhruvilwortal** [comment]
Please explain how to solve this: Reject the requested READ_CALL_LOG permission
