### ISSUE TITLE
No podspec found for `react-native-callkeep` in `../node_modules/react-native-callkeep`

### ISSUE THREAD

**Issue by sambegin** [react-native-webrtc/react-native-callkeep#41]
When using [installation with cocoapods](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/docs/ios-installation.md#installation-with-cocoa-pods) steps, pod installation fails with this error.

<img width="648" alt="Screen Shot 2019-04-29 at 10 50 56 AM" src="https://user-images.githubusercontent.com/6645382/56904768-f15e1d80-6a6c-11e9-9458-452218aeb677.png">

**Comment by sambegin** [comment]
To resolve the problem: https://github.com/react-native-webrtc/react-native-callkeep/pull/42

**Comment by manuquentin** [comment]
Fixed in #42 thanks !
