### ISSUE TITLE
[Android] "Activity doesn't exist" - Failed setup RNCallkeep in killed state

### ISSUE THREAD

**Issue by er1cAk** [react-native-webrtc/react-native-callkeep#410]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on: Emulator API 27, 28
 - [x] Android
 - [ ] iOS

## Description

I trying to use callkeep for voip incoming calls. Info about incoming call will arrive throught the "data-only" notification (FCM). After received notification (handled by headless task). I trying to initialize RNCallKeep.setup but It will throw  the error "Activity doesn't exist". 

Foreground and Background works fine.

## Steps to Reproduce

1. Kill the running application.
2. Try to initialize RNCallKeep from headless task of FCM.

## Versions
    - Callkeep: "git+https://github.com/react-native-webrtc/react-native-callkeep.git"
    - React Native: 0.63.4
    - iOS: 14.5
    - Android: API 27, 28
    - Phone model: Pixel 2
    - @react-native-firebase/messaging: "^11.4.1",

## Logs

```
[Thu May 06 2021 19:14:03.596]  WARN     FCM remote message
[Thu May 06 2021 19:14:03.597]  LOG      {"nativeStackAndroid":[],"userInfo":null,"message":"Activity doesn't exist","code":"E_ACTIVITY_DOES_NOT_EXIST","line":2416,"column":45,"sourceURL":"http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"}
[Thu May 06 2021 19:14:03.950]  LOG      Running "main" with {"rootTag":1}
```

## Code implementation

```javascript
// Registering headless task
messaging().setBackgroundMessageHandler(
           async (remoteMessage: RemoteMessage) => {
                console.warn('FCM remote message');
                await CallKeepServiceI.init();
                CallKeepServiceI.displayIncomingCall();
            }
);
```

**Comment by vuletuan** [comment]
Don't use the `RNCallKeep.setup(options); `in the background.  Register manually with: 
```
RNCallKeep.registerPhoneAccount();
RNCallKeep.registerAndroidEvents();
RNCallKeep.setAvailable(true);
```

**Comment by Freeminderus** [comment]
@er1cAk hey, did you solve the problem? I'm having same issue

**Comment by Andriiklymiuk** [comment]
Have anyone solved the problem?

**Comment by er1cAk** [comment]
I solved it by splitted intialization for iOS and android.

For android I calling this code, every time when notification will arrive
```
     RNCallKeep.registerPhoneAccount();
     RNCallKeep.registerAndroidEvents();
     RNCallKeep.setAvailable(true);
```

**Comment by krishnamistry17** [comment]
Hi 
react-native-callkeep not working If i kill the running application.
Has anyone solved the problem?

**Comment by kingofday** [comment]
can some one please answer this:
[here](https://stackoverflow.com/questions/73654854/show-display-incoming-call-when-receiving-fcm-push-with-inactive-app-statehttps://stackoverflow.com/questions/73654854/show-display-incoming-call-when-receiving-fcm-push-with-inactive-app-state)

**Comment by HalilFocic** [comment]
@Andriiklymiuk Can you please provide code,even tho I did exactly that I still don't get notification

**Comment by Andriiklymiuk** [comment]
@HalilFocic well, I haven’t fixed it myself)

**Comment by HalilFocic** [comment]
I fixed it, is it still an issue for you?

**Comment by Andriiklymiuk** [comment]
@HalilFocic how had you fixed that?

**Comment by HalilFocic** [comment]
You need to manually  change RNCallKeepModule.java file after installing node modules. You need to alter the hasPermissions function like this https://github.com/react-native-webrtc/react-native-callkeep/pull/576/files.

After that, in your background message handler you call theese functions before calling RNCallKeep.displayIncmoingCall(cfg) 
` await RNCallKeep.registerPhoneAccount(configSetup);
    await RNCallKeep.registerAndroidEvents();
    await RNCallKeep.setAvailable(true);`

**Comment by AbdulBsit** [comment]
Hey, @HalilFocic, I have tried your solution, its not working for me, can you please provide me which version of the release you are using for this module, I am getting this error `registerPhoneAccount expects 1 argument, got 0`, even i am passing the config, can you please show me your code snippet, and version number for this library

**Comment by HalilFocic** [comment]
I am using same version as you     `react-native-callkeep": "^4.3.3`

Before reading code below PLEASE make sure you are actually receiing notifications in background mode. Try following things:
1. Setting background message handler to have a console.log so you can the that message arrived
2. If message is arriving, kill your app and try to send notification again
3. After few seconds,your index.js bundle should load and output the console.log again
4. If that is not working,please tag me and I will send you the config for FCM message needed to work
This is how my RNCallKeep config looks:

```
const callKeepConfig = {
  ios: {
    appName: "appname",
  },

  android: {
    alertTitle: "Permissions required",
    additionalPermissions: [],
    alertDescription: "This application needs to access your phone accounts",
    cancelButton: "Cancel",
    additionalPermissions: [],
    okButton: "ok",
  },
};

```
This is what my background notification handler looks like:

```
messaging().setBackgroundMessageHandler(async (msg) => {
  if (msg.data.type === "receive_call") return handleCallNotification(msg.data);
});

```
handleCallNotification function:
```
const handleCallNotification = async (data) => {
  console.log("Trting to call");
  if (Platform.OS === "android") await RegisterCallKeep();
  notificationContent = data;
  const uid = getNewUuid();
  currentUid = uid;
  RNCallKeep.displayIncomingCall(
    uid,
    data.expert_name,
    data.expert_name,
    "generic",
    true
  );
};

```
My RegisterCallKeepFunction(This gets called only in Android Platforms)

```
const RegisterCallKeep = async () => {
    RNCallKeep.removeEventListener("answerCall", answerCall);
    RNCallKeep.removeEventListener("endCall", endCall);
    await RNCallKeep.registerPhoneAccount(configSetup);
    await RNCallKeep.registerAndroidEvents();
    await RNCallKeep.setAvailable(true);
    RNCallKeep.addEventListener("answerCall", answerCall);
    RNCallKeep.addEventListener("endCall", endCall);
};
```
Hope it helps

**Comment by AbdulBsit** [comment]
Yeah, I have checked, i am receiving the fcm message in background state, all logs coming in, but its not invoking the call UI, Its just something related to registerPhoneAccount, its not working for me.

Well Thanks anyways, Also do you have your fork of the changes you made to the library, or you just directly manipulated the callKeep library on node_modules

If you have any fork, I can easily check the diff, may be something else i am missing apart from all things. 

Also which react-native version you are using?

**Comment by HalilFocic** [comment]
My rn native version is 0.68 on the project. I jusyt manipulated the RNCallKeepModule.java as shown in the link i provided in comment before.

**Comment by AbdulBsit** [comment]
Okay, I am using 0.63 may be because of that, things are not working as expected, Thanks anyways :)

**Comment by tarunebizon** [comment]
> You need to manually change RNCallKeepModule.java file after installing node modules. You need to alter the hasPermissions function like this https://github.com/react-native-webrtc/react-native-callkeep/pull/576/files.
> 
> After that, in your background message handler you call theese functions before calling RNCallKeep.displayIncmoingCall(cfg) ` await RNCallKeep.registerPhoneAccount(YOUR_CONFIG)`
> 
> ` await RNCallKeep.registerAndroidEvents()`
> 
> ` await RNCallKeep.setAvailable(true)`

this worked, thanks
