### ISSUE TITLE
how to handle call keep in background and killed stage

### ISSUE THREAD

**Issue by prasanthvenkatachalam** [react-native-webrtc/react-native-callkeep#434]
incoming call UI  is not visible if app is in background or killed stage (Both in IOS and android). How to Overcome this issue, Kindly help

**Comment by namnm** [comment]
You need to trigger displayIncomingCall **inside Push Notification handler**
In android it can be called inside your regular javascript handler
In ios you must call from native side: https://github.com/react-native-webrtc/react-native-callkeep#pushkit

**Comment by khanhduy62** [comment]
@namnm Do you have any code example for setting up for android?

**Comment by namnm** [comment]
@khanhduy62 We have an opensource repo here, you can take a look at:
https://github.com/brekekesoftware/brekekephone/blob/master/src/utils/callkeep.ts
https://github.com/brekekesoftware/brekekephone/blob/master/src/utils/PushNotification.android.ts

**Comment by prasanthvenkatachalam** [comment]
solved using https://www.npmjs.com/package/react-native-incoming-call-android. Working in background and killed stage

**Comment by fukemy** [comment]
thanks, i will read it
