### ISSUE TITLE
cant able to invoke android app in Background

### ISSUE THREAD

**Issue by prasanthvenkatachalam** [react-native-webrtc/react-native-callkeep#444]
Cant able to invoke android app from  Background or killed stage. I have tried with react-native-invoke-app ,  RNCallKeep.backToForeground(), but no improvement. Incoming UI is showing when app is in Background or Killed Stage but when interaction happens, app is not coming from background to foreground. help needed

**Comment by Andriiklymiuk** [comment]
@prasanthvenkatachalam have you solved it? same issue

**Comment by namnm** [comment]
Have you tried `RNCallKeep.backToForeground()`?
https://github.com/react-native-webrtc/react-native-callkeep#backtoforeground

**Comment by Andriiklymiuk** [comment]
Yeah, thanks, it works, but I decided to use Linking.openUrl(“app://app”) instead, to make it work both for iOS and android

**Comment by namnm** [comment]
@Andriiklymiuk On ios by default your app will open if you accept the call, we didnt need to manually open our app. It doesnt work like that on your side?

**Comment by Andriiklymiuk** [comment]
Actually, it doesn’t always open on iOS too, if user answers the call, while there is another app in foreground and the main app was killed/force closed before. Many times happens also on android (after answering the cal I see only audio call screen and app isn’t opened to foreground). Interestingly, it only happens, if there is another app is opened, but doesn’t happen if no app was opened.

Probably I use not the newest version of callkeep, will try to update and see what helps. Still investigating

**Comment by prasanthvenkatachalam** [comment]
> Have you tried `RNCallKeep.backToForeground()`?
> https://github.com/react-native-webrtc/react-native-callkeep#backtoforeground

yes, but no improvement

**Comment by prasanthvenkatachalam** [comment]
> @prasanthvenkatachalam have you solved it? same issue

still not solved

**Comment by namnm** [comment]
How do you call the method? Is it inside a notification handler?

**Comment by lazynewt** [comment]
How can this not work for so many people when it is clearly documented? Is anyone able to bring a paused/background application to the foreground? Can anyone that can please provide insight as to what they have done other than [yarn add] > [import RNCallKeep] > [RNCallKeep.backToForeground()] ?? Thanks.

**Comment by prasanthvenkatachalam** [comment]
> How do you call the method? Is it inside a notification handler?

Yes, also I tried it in headless js

**Comment by namnm** [comment]
I really dont know, most of people got it working, I have it working in my app too. The flaw must be in your code. May be you can create a new fresh RN app and try reproduce from there?

**Comment by prasanthvenkatachalam** [comment]
I am using like this. when user taps answercall button, below function will be called, But in App is not comming to foreground. I also used   RNCallKeep.backToForeground();. Help needed

function onAnswerCallAction(event) {
  console.log("onAnswerCallAction");
  console.log(event, "onAnswerCallAction");
  RNCallKeep.backToForeground();
 Linking.openURL("rawcaster://UserList/" + `${21}`);
  RNCallKeep.endAllCalls();
}

**Comment by prasanthvenkatachalam** [comment]
Its  RNCallKeep.backToForeground() Working in Android Version 11 but not in Android 10 and below.

**Comment by prasanthvenkatachalam** [comment]
solved using https://www.npmjs.com/package/react-native-incoming-call-android

**Comment by prasanthvenkatachalam** [comment]
solved using https://www.npmjs.com/package/react-native-incoming-call-android. Working in background and killed stage

**Comment by prasanthvenkatachalam** [comment]
solved using https://www.npmjs.com/package/react-native-incoming-call-android. Working in background and killed stage

**Comment by vohoangankhanh** [comment]
> solved using https://www.npmjs.com/package/react-native-incoming-call-android. Working in background and killed stage

this package is stolen from https://github.com/bkdev98/react-native-incoming-call

**Comment by Dat-Mobile** [comment]
> RNCallKeep.backToForeground() Working in Android Version 11 but not in Android 10 and below.

I'm using xiaomi 11 Android 11, and it doesn't work

**Comment by Dat-Mobile** [comment]
oh this [comment](https://github.com/react-native-webrtc/react-native-callkeep/issues/477#issuecomment-979736303) helped me
