### ISSUE TITLE
Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by fastmanu** [react-native-webrtc/react-native-callkeep#45]
Hi Callkeep team,

I'm getting this error on android when running the sample code. I tried to unlink and link the package again, and finally checked everything manually, but it keeps happening.

This error disappears if i manually authorize my to access the phone (settings -> Apps permissions -> myapp -> permissions -> phone).

Any idea ?

Manu

![Screenshot_1557148066](https://user-images.githubusercontent.com/463287/57228368-f0506180-7013-11e9-9825-eb9cda875f38.png)
 
react-native-cli: 2.0.1
react-native: 0.59.5

**Comment by manuquentin** [comment]
Hi @fastmanu !
I think it's fixes in #30, I'll release a new version soon with this fix

**Comment by fastmanu** [comment]
Bonjour Manu, 

That was quick :) Thanks for your help 👍

**Comment by manuquentin** [comment]
I've published a `2.0.2`. Can you check if the issue still persist ?

Regards,
Manu

**Comment by sambegin** [comment]
Can confirm it is working with 2.0.2. Thanks !

**Comment by fastmanu** [comment]
Issue fixed, thank you manu ;)
