### ISSUE TITLE
help: how to call/listen to ``RNCallKeepBackgroundMessage`` even from ``registerHeadlessTask``

### ISSUE THREAD

**Issue by beqramo** [react-native-webrtc/react-native-callkeep#456]
Hi,

 I'm a little confused, I don't understand how to call this headless task, I tried push notifications but nothing was login in any console. 

As I understand it automatically listens to the push notification when the app is killed but my function isn't triggering.

should I add any specific property in the push notification payload?

thank you in advance.

**Comment by beqramo** [comment]
closing, correct way is to send data only push notification

**Comment by rajasekhar911** [comment]
Hi,

If you are asking about the incoming call notifications, then you need to use react-native-firebase lib for that. Specifically, the messaging().setBackgroundMessageHandler and invoke RNCallKeep.displayIncomingCall  from there.

**Comment by beqramo** [comment]
@rajasekhar911  
Thanks for your help

But what is the point of having RNCallKeepBackgroundMessage headlessTask?

**Comment by rajasekhar911** [comment]
@beqramo 
from the doc, that is related to outgoing call from the phone. have not used it :)

**Comment by khanhduy62** [comment]
@rajasekhar911 Do you have any code example for setting up for android?

**Comment by rajasekhar911** [comment]
needs to be incoked on app launch

`RNCallKeep.setup({
        ios: {
          appName: 'appName'
        },
        android: {
          alertTitle: 'Permissions required',
          alertDescription:
            'This application needs to access your phone accounts',
          cancelButton: 'Cancel',
          okButton: 'ok',
          foregroundService: {
            channelId: 'channelId',
            channelName: 'channelName,
            notificationTitle: 'notificationTitle'
          }
        }
      });
      RNCallKeep.setAvailable(true);`

**Comment by beqramo** [comment]
@rajasekhar911 How do you handle reject cases on Incomming calls?
Especially on IOS?

**Comment by rajasekhar911** [comment]
@beqramo still trying to figure it out :) trying to use react-native-background-timer. have not targetted IOS yet.

**Comment by Romick2005** [comment]
If there are WebSocket connection already established then via 
`RNCallKeep.endCall(callUUID) `
or regular push notification for iOS and processing them in native part:
```
[RNCallKeep endCallWithUUID: callUUID reason: [reasonId intValue]];
completion();
```

**Comment by beqramo** [comment]
@Romick2005  that code snippet is really helpful thanks. 
 but my question is a little different:
 I meant how to know if another user who received calls from another one rejects the call then the app is killed? I see "endCall" event when the app is opened but I can't get anything when app is killed
 
 Thanks for your time

**Comment by Romick2005** [comment]
@beqramo In that case I send rest api request to notify server ant then from server to other party via WebSocket or Push Notification as I wrote you before. Please take a look at [this](https://github.com/react-native-webrtc/react-native-callkeep/issues/330#issuecomment-799525290) my old answer.

**Comment by beqramo** [comment]
@Romick2005 thank you, I think I'm out of questions :D,
I can continue building it now, 

thanks again.

**Comment by nero2009** [comment]
@beqramo Do you know how to handle this scenario on android 

> @rajasekhar911 How do you handle reject cases on Incomming calls?
> Especially on IOS?

**Comment by beqramo** [comment]
On android there is no problem receiving call reject. You can listen endcall action

**Comment by nero2009** [comment]
Do you send a push notification or use a websocket connection?
Can you share a code snippet?

**Comment by beqramo** [comment]
I send push notifications with headless js and listening that notification and after that I trigger call UI. On reject I send it with REST.I can't share my codes sorry

**Comment by nero2009** [comment]
Sorry I mean how do you reject an incoming call before the person receiving the call picks up? Basically the android version of the below code.

> If there are WebSocket connection already established then via
> `RNCallKeep.endCall(callUUID) ` on js side
> or regular push notification for iOS and processing them in native part:
> 
> ```
> [RNCallKeep endCallWithUUID: callUUID reason: [reasonId intValue]];
> completion();
> ```

**Comment by beqramo** [comment]
You can just call endAllCalls or something, and to trigger that you can use data push notification, with type reject and on that type you will end all call

**Comment by nero2009** [comment]
Thank you, I will try that.

**Comment by newme616** [comment]
I managed to get it to work if the app is open. Unfortunately it doesn't work with the app closed. I guess I would have to implement it in Objective C in the AppDelegate, but I honestly don't know the language at all. 

Does anyone has a sample on how to add a notification listener and I guess then trigger RN CallKeep endCallwithUUID?

**Comment by mkhoussid** [comment]
> I managed to get it to work if the app is open. Unfortunately it doesn't work with the app closed. I guess I would have to implement it in Objective C in the AppDelegate, but I honestly don't know the language at all.
> 
> Does anyone has a sample on how to add a notification listener and I guess then trigger RN CallKeep endCallwithUUID?

Did you manage to figure it out?
