### ISSUE TITLE
HELP: get rid of "Permissions required" from android

### ISSUE THREAD

**Issue by beqramo** [react-native-webrtc/react-native-callkeep#460]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description

Hi everyone,

I'm building FB Messenger like application and  I faced a problem when the app requires permission to access phone accounts on first open and I feel like this is not what for example FB messenger does and is there any way to remove it or how I can make FB messenger like calls? 

Thanks in advance.

<img src="https://user-images.githubusercontent.com/40486471/126833313-a2218e44-3a9e-419b-ba7a-d6310425b0fd.jpg" width="300"> <img src="https://user-images.githubusercontent.com/40486471/126833311-2f2008b4-bf7b-4695-ab0a-6abde8e4d560.jpg" width="300"> <img src="https://user-images.githubusercontent.com/40486471/126833308-41e60bd9-8ef1-41c2-8530-ddf10206397c.jpg" width="300">

**Comment by manuquentin** [comment]
Hi @beqramo,

Callkeep is using a phone account by default. To avoid this behaviour, you should use the [self managed mode](https://github.com/react-native-webrtc/react-native-callkeep#android-self-managed-mode).

**Comment by beqramo** [comment]
Hi @manuquentin, thanks for your answer, 
 One thing that I don't understand fully is how to render react native code in my custom UI?

**Comment by manuquentin** [comment]
You should listen to the `showIncomingCallUi` event and display you UI at this time.
You can make a test with [https://github.com/bkdev98/react-native-incoming-call#readme](react-native-incoming-call#readme).

**Comment by beqramo** [comment]
So, you mean that on ``showIncomingCallUi`` I should open my app and show my own view right?
I thought that it was a separate react node tree, so it would be fast to render. 
Thanks

**Comment by manuquentin** [comment]
To open the app in headless mode when you app is killed, please refer [to the doc](https://github.com/react-native-webrtc/react-native-callkeep#receiving-a-call-when-the-application-is-not-reachable).

When your JS bridge will be available, the `showIncomingCallUi` might be available in the `getInitialEvents` method or in the `didLoadWithEvents` event.

**Comment by beqramo** [comment]
thanks
