### ISSUE TITLE
selfManaged: true does not show native incoming on android.

### ISSUE THREAD

**Issue by duypxd** [react-native-webrtc/react-native-callkeep#465]
I get notification when there is a call: `Tap for more information or to stop the app`
I am using RNCK v4.2.0 and `selfManaged: true`:
When I use `selfManaged: true ` it is not possible to show incoming screen on android.
`RNCallKeep.displayIncomingCall` not working.
- If I set `selfManaged: false` then RNCK will ask for phone access, then I get incoming screen.
- Anyone have more documentation on how to use it? I went through the docs but I think it supports custom incoming screen in app. So how about the app in the background/lock app?

@manuquentin @jonastelzio Please!

**Comment by jonastelzio** [comment]
@xuanduyrn did you implement all the code needed to display your own incoming call screen? i.e. a notification that's configured to show as a full screen activity?

Please try launching your incoming call ui separately through some mechanism so you're certain it's working, before trying to tie it into call keep. My guess would be that it's not properly implemented.
