### ISSUE TITLE
why is calling accounts permission necessary?

### ISSUE THREAD

**Issue by cdg720** [react-native-webrtc/react-native-callkeep#471]
Asking for the calling accounts permission shows an atypical permission page (https://github.com/react-native-webrtc/react-native-callkeep/issues/189). Well-known VoIP apps (whatsapp, snapshot, discord ) don't ask for it and I am wondering why callkeep needs it to display incoming calls.

**Comment by manuquentin** [comment]
Hello @cdg720,
As replied in #460, the default behaviour of callkeep is to use a phone account.

To change it, you have to use the [self managed mode](https://github.com/react-native-webrtc/react-native-callkeep#Android-Self-Managed-Mode) of callkeep

**Comment by cdg720** [comment]
@manuquentin thank you!
