### ISSUE TITLE
Start a call from recent calls

### ISSUE THREAD

**Issue by josaric** [react-native-webrtc/react-native-callkeep#490]
## Description
I want to start a call from recent calls. In my contacts I can choose from which app I want to start a call and it offers me: WhatsApp, Viber, telegram, etc... and my app also, but when I click on it, it just opens.

## Steps to Reproduce

I assume I need to register a listener for something like that and I did with "didReceiveStartCallAction", but it's not working.

**Comment by josaric** [comment]
Manage to do it with "didLoadWithEvents" event listener but only while app is fully closed (not working in foreground).

**Comment by josaric** [comment]
Same issue as: https://github.com/react-native-webrtc/react-native-callkeep/issues/397

**Comment by shawarmaz** [comment]
why was this closed ?

**Comment by josaric** [comment]
@shawarmaz duplicated? https://github.com/react-native-webrtc/react-native-callkeep/issues/397
