### ISSUE TITLE
Cannot use voice on android when accepting incoming calls.

### ISSUE THREAD

**Issue by xuanduyrn** [react-native-webrtc/react-native-callkeep#527]
Cannot use voice on android when accepting incoming calls.
- RNCK: 4.0.1

- When app is closed and phone is locked - You Connects but no audio from Me
- When app is closed and phone is unlocked - You Connects but no audio from Me

**Comment by xuanduyrn** [comment]
Closed
it involves setting RNCallkeep.setup at index.js

**Comment by fukemy** [comment]
can u explain more? Thanks

**Comment by danishkhawaja98** [comment]
Hi @xuanduyrn 
Can you explain your solution with us?

Thanks

**Comment by devilabhi** [comment]
Answer must be explained so that someone may use that and then only issue must be closed
