### ISSUE TITLE
Ability to use react-native-callkeep when app is backgrounded/killed

### ISSUE THREAD

**Issue by sunweiyang** [react-native-webrtc/react-native-callkeep#55]
The react-native-callkeep library works when the app's JS is active (open/backgrounded for Android, open for iOS). However, the react-native-callkeep JS API, as documented in the readme, doesn't work when the app is in the other states (killed for Android, backgrounded/killed for iOS).

Can react-native-callkeep possibly be made to work in those scenarios (i.e. from a push notification via a native notification service, etc.)?

**Comment by manuquentin** [comment]
Hi @sunweiyang.
I've answered to this question in #21.

To be able to wake up your application you should use `PushKit` on ios and `BackgroundMessage` on Android with Firebase.
