### ISSUE TITLE
No events triggered on ios 

### ISSUE THREAD

**Issue by williemccool** [react-native-webrtc/react-native-callkeep#559]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] iOS

## Description
On Android, it works fine but on ios, neither "answerCall" nor "didLoadwithEvents" work. We get the call UI and after clicking Answer, the ongoing call screen persists and none of the events are triggered. 
This is a normal notification push from Onesignal and happening on App in foreground.
We have not tried with voip push notifications since app is still in foreground.

## Versions
    - Callkeep: 4.3.2
    - React Native: 0.62.2
    - iOS: Target 15, testing on 15.4
    - Phone model: Iphone 13 Pro

## Logs

```
Paste here
```

**Comment by ajitdas123** [comment]
@williemccool How did you manage to resolve this? I am facing the same problem.

**Comment by thexdd** [comment]
Having the same problem. Copy-pasted the example file (RNCallKeepExample), added the component to my app, called setup(). I am getting no events unfortunately. Am I missing anything?

**Comment by fukemy** [comment]
same problem, not working
