### ISSUE TITLE
Microphone is muted when there is another incoming call

### ISSUE THREAD

**Issue by liemdo** [react-native-webrtc/react-native-callkeep#560]
# Bug report
When I'm on a call and there is a second incoming call or a system notification sound, the other party can't hear me speaking until the second call stops. 

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Versions
    - Callkeep: 4.3.2
    - React Native: 0.68.0
    - iOS: 15.3.1
    - Android: 
    - Phone model: iphone 12

**Comment by saheemhussainchicmic** [comment]
Did you find a solution? @liemdo

**Comment by slootmaekersdirk** [comment]
same issue here, did you find a solution?

**Comment by slootmaekersdirk** [comment]
FYI : found the issue in my case. My first call as an outbound call, and I didn't do a rncallkeep.startCall() , so the call was not monitored by the OS. after doing that everything started working

hope this helps
Dirk
