### ISSUE TITLE
`displayIncomingCall` no longer working when app is awaken after being killed since version 4.3.3

### ISSUE THREAD

**Issue by glesperance** [react-native-webrtc/react-native-callkeep#577]
# Bug report

~~- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.~~
^ Not applicable since AFAIK the example app doesn't implement a mechanism to be waken when killed.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description
RNCallKeep is unable to successfully evoke `displayInconmingCall`  when the app is awaken after being killed. An example of a situation presenting this issue is when a push notification is received, and the app needs alert the user of an incoming call.

I have traced the bug down to this commit: https://github.com/react-native-webrtc/react-native-callkeep/commit/35d6e7f776e68cefb3854bfade8fec82b363b2be

My understanding is that:

1. `displayInconmingCall()` now depends on `hasPermissions()` to return `true`;
2.  `hasPermissions()` require `getCurrentReactActivity()` to return a valid activity;Give
3.  `getCurrentReactActivity()` requires a react context which is not available when launching after being killed.

Given that permissions can be checked by the application, I propose that we revert https://github.com/react-native-webrtc/react-native-callkeep/commit/35d6e7f776e68cefb3854bfade8fec82b363b2be since it introduces a major bug, and goes against the principle of separation of concerns

## Versions
    - Callkeep: 4.3.3
    - React Native: 0.64.2
    - iOS: n/a
    - Android: 11
    - Phone model: Samsung Galaxy A32 5G

## Logs

```
$ adb logcat | grep RNCallKeepModule
05-09 19:53:53.111 10226 15824 D RNCallKeep: [RNCallKeepModule] getInstance : ok
05-09 19:53:53.111 10226 15824 D RNCallKeep: [RNCallKeepModule] constructor
05-09 19:53:53.119 10226 15824 D RNCallKeep: [RNCallKeepModule] updating react context
05-09 19:53:58.511 10226 15832 D RNCallKeep: [RNCallKeepModule] registerPhoneAccount
05-09 19:53:58.525 10226 15832 D RNCallKeep: [RNCallKeepModule] registerEvents
05-09 19:53:58.525 10226 15832 D RNCallKeep: [RNCallKeepModule] startObserving, event count: 0
05-09 19:53:58.583 10226 15832 W RNCallKeep: [RNCallKeepModule] displayIncomingCall ignored due to no ConnectionService or no phone account
```

**Comment by grit96** [comment]
@glesperance  does https://github.com/react-native-webrtc/react-native-callkeep/pull/576 fix this?
