### ISSUE TITLE
Report end call if caller stops the call before the callee picks up

### ISSUE THREAD

**Issue by newme616** [react-native-webrtc/react-native-callkeep#597]
# Bug report

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description
I am trying to end an incoming call before the callee accepts/picks the call using callkeep. 
What I got so far thanks to @nero2009  and @Romick2005 ( https://github.com/react-native-webrtc/react-native-callkeep/issues/461 ) 

Send another push notification that has a data property e.g isMissedCall then call Callkeep method RNCallKeep.reportEndCallWithUUID(uuid, reason); to end the call.The notifcation gets delivered but firebase OnMessageReceived is never called when the call is actively ringing.

This works perfectly if the app is in foreground. I handle this on the JS Side, no problem, but if the app is in background or even swiped away it doesn't work. So  I am trying to implement this in the AppDelegate

This is what I got in the App Delegate

```
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler{
    NSString *callId = [[NSUserDefaults standardUserDefaults] stringForKey:@"callId"];
    BOOL *isMissedCall = [[userInfo objectForKey:@"isMissedCall"] boolValue];
    
    if (isMissedCall) {
    int reasonId = 6;
    [RNCallKeep endCallWithUUID: callId reason: reasonId];
    }

```
I don't know Obj C, so please excuse the bad code. Problem is this never gets called if I send a push notification. I don't know why, so I can't even log the output. 

I am using OneSignal for voip and normal pushes (2 different app ids)

I also checked: 
https://github.com/react-native-webrtc/react-native-callkeep/issues/418

## Versions
    - Callkeep: 4.3.3
    - React Native: 0.64.3
    - iOS: 15.5

**Comment by DR7777** [comment]
I have the same issue, did you find a solution?

**Comment by newme616** [comment]
@DR7777 I now managed to fix it. Had some error in the Obj C Code, also it should be below `didReceiveIncomingPushWithPayload:`

here is the final code:
`-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler{
    NSString *callId = [[NSUserDefaults standardUserDefaults] stringForKey:@"callId"];
    BOOL isMissedCall = [[userInfo objectForKey:@"isMissedCall"] boolValue];
    NSLog(@"didReceiveRemoteNotification: %@", userInfo);
    if (isMissedCall) {
    int reasonId = 6;
    [RNCallKeep endCallWithUUID: callId reason: reasonId];
    }

    completionHandler(UIBackgroundFetchResultNewData);
}`
