### ISSUE TITLE
Update explanation in readme

### ISSUE THREAD

**Issue by wumke** [react-native-webrtc/react-native-callkeep#61]
I'm looking for a better incoming call-notification than push notifications for a WebRTC videocalling app, when i read the readme it is not immediately clear for me what happens on ios and android when the answer button is pressed?
Will my app be opened with some extra data?
Can we use it with WebRTC (and custom UI) instead of VOIP?
Can it be used when app is not active or in background?

_Aside from this., great that someone converted the callkit lib into a cross platform one! I really hate one platform react-native packages or packages that behave completely different on both platforms!_

**Comment by manuquentin** [comment]
Hi @wumke !
You're right, I'll update the documentation.

It's depend on the platform (iOS or Android) the behaviour is not totally the same.
On locked screen for example, both will display the native incoming call UI in full screen.
When you press the answer button, the `answerCall` method is called, and them it's up to you to do whatever you want (WebRtc, VOIP, ...).
It can be used when the app is in background or when the phone is locked.
If you're using Websocket to receive events, beware that some constructor may close the connection after ~10/15mn of inactivity.
For that case and when the app is killed (closed), we recommend to use [pushkit](https://github.com/ianlin/react-native-voip-push-notification) on iOS and firebase background message (https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages#4)-(Optional)(Android-only)-Listen-for-FCM-messages-in-the-background.) to wake up our app so we are able to call displayIncomingCall.

I'll update the readme with all this explanation, tell me if it's not clear for you.

**Comment by wumke** [comment]
That is a short but complete answer to all my questions... thank you for the quick response!

I'll give it a try when I find some time, I trigger users by push notification and even force close my app when it goes to background to reduce power/memory consumption of the connection with websocket signaling server and camera input source.
