### ISSUE TITLE
How to implement self managed mode

### ISSUE THREAD

**Issue by matsuda-argano** [react-native-webrtc/react-native-callkeep#613]
First of all, I would like to thank the author of such a wonderful library.

I have a few questions about how to implement Self Managed Mode.

Please understand that my questions may be out of line due to my limited experience in native development. Please also forgive my poor English.

When an incoming call comes in while the app is not running, I would like to start the app and display the original incoming call screen, but I don't know how to implement this.

I would like to ask you some questions together with the implementation procedure of Self Managed Mode in the README.

`On an incoming call, from react native, call RNCallKeep.displayIncomingCall`.

When and where should I call `RNCallKeep.displayIncomingCall` for this procedure?

`When showIncomingCallUi is fired, you must show an incoming call UI. `

Can the display of the incoming call UI be controlled by JavaScript?
Also, is it possible to use ReactNative components for the incoming call UI? Do I need to create the incoming UI natively?

Sample code would be greatly appreciated.
Thank you in advance for your response.

**Comment by matsuda-argano** [comment]
The implementation PR said what we wanted to know.
https://github.com/react-native-webrtc/react-native-callkeep/pull/395

**Comment by ericlyoung** [comment]
"When an incoming call comes in while the app is not running, I would like to start the app and display the original incoming call screen, but I don't know how to implement this."

nobody on earth knows how to do this.

**Comment by KevMac19** [comment]
> "When an incoming call comes in while the app is not running, I would like to start the app and display the original incoming call screen, but I don't know how to implement this."
> 
> nobody on earth knows how to do this.

Can you share your implementation? I am able to show a native calling screen while app is not running(killed state).
