### ISSUE TITLE
`startCall` triggers a Cellular Call on devices with a work profile

### ISSUE THREAD

**Issue by homersimpsons** [react-native-webrtc/react-native-callkeep#622]
# This is not an issue with RNCallKeep, see comment below for context.

(This is the original reported issue, but the issue is not about samsung phones)

# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description

On "Galaxy S20 FE (OneUI 4.1)" and "Samsung A32" when the program use `startCall`, the phone triggers a cellular call to the provided phone number instead of using the app's phone account.

## Steps to Reproduce

1. setup RNCallKeep
2. Trigger a call with `startCall`
  1. This does trigger a cellular call to the provided phone number, with an inexistent phone number the "operator" will answer that this number is not reachable

## Versions
    - Callkeep: 8fef467243adc52dc85e732f806472f3a8ebd4a8 (latest version and some commits, I needed a fix for background calls and cannot go to android API level 31+)
    - React Native: 0.65.1
    - iOS: ~
    - Android: 12 (OneUI 4.1)
    - Phone model: Galaxy S20 FE / Samsung A32

## Logs

I do not have relevant logs for the moment.

**Comment by ThibBal** [comment]
Hello,

I'm having the same issue on my side. No solution found for the moment and no idea on the source of this problem. Does somebody else encountered this scenario and succeed into fixing it?

Thanks for your help!

**Comment by homersimpsons** [comment]
When using an Android work profile (https://support.google.com/work/android/answer/6191949?hl=en) and this application, the `startCall` action may trigger a native (cellular) call.

Digging a bit in the issue, it looks like this is an expected behavior in android.

In fact we can see in [`~aosp/src/com/android/server/telecom/CallIntentProcessor.java#165`](https://android.googlesource.com/platform/packages/services/Telecomm/+/master/src/com/android/server/telecom/CallIntentProcessor.java#165):

```java
if (!callsManager.isSelfManaged(phoneAccountHandle,
        (UserHandle) intent.getParcelableExtra(KEY_INITIATING_USER))) {
    boolean fixedInitiatingUser = fixInitiatingUserIfNecessary(context, intent);
    // Show the toast to warn user that it is a personal call though initiated in work
    // profile.
    if (fixedInitiatingUser) {
        Toast.makeText(context, Looper.getMainLooper(),
        context.getString(R.string.toast_personal_call_msg),
        Toast.LENGTH_LONG).show();
    }
} else {
    Log.i(CallIntentProcessor.class,
    "processOutgoingCallIntent: skip initiating user check");
}
```

And in [`~aosp/src/com/android/server/telecom/CallIntentProcessor.java#214`](https://android.googlesource.com/platform/packages/services/Telecomm/+/master/src/com/android/server/telecom/CallIntentProcessor.java#214):

```java
/**
  * If the call is initiated from managed profile but there is no work dialer installed, treat
  * the call is initiated from its parent user.
  *
  * @return whether the initiating user is fixed.
  */
static boolean fixInitiatingUserIfNecessary(Context context, Intent intent) {
    final UserHandle initiatingUser = intent.getParcelableExtra(KEY_INITIATING_USER);
    if (UserUtil.isManagedProfile(context, initiatingUser)) {
        boolean noDialerInstalled = DefaultDialerManager.getInstalledDialerApplications(context,
                initiatingUser.getIdentifier()).size() == 0;
        if (noDialerInstalled) {
            final UserManager userManager = UserManager.get(context);
            UserHandle parentUserHandle =
                    userManager.getProfileParent(
                            initiatingUser.getIdentifier()).getUserHandle();
            intent.putExtra(KEY_INITIATING_USER, parentUserHandle);
         
            Log.i(CallIntentProcessor.class, "fixInitiatingUserIfNecessary: no dialer installed"
                    + " for current user; setting initiator to parent %s" + parentUserHandle);
            return true;
        }
    }
    return false;
}
```

So what we can understand is that:
1. The behavior won't happen in self-managed mode (`if (!callsManager.isSelfManaged(...)`)
2. This happen because there is `noDialerInstalled` in the work profile.
