### ISSUE TITLE
Using regular call prompts SIM select

### ISSUE THREAD

**Issue by HalilFocic** [react-native-webrtc/react-native-callkeep#632]
- Reproduced on:
 -  Android

## Description
Hi, I implemented the RNCallKeep, while iOS works fine. I get this wierd bug on Android. The call is working but I don't think this is how it is supposed to work. Every time I want to use regular call, I get prompted asking if I want to use my SIM provider or my app(Mendy).
Anyone encountered something similar?
![image](https://user-images.githubusercontent.com/56510805/203022971-753f1493-5e92-4470-80d3-a84473921834.png)

**Comment by khangdev0201** [comment]
did you use SAMSUNG devices ?

**Comment by SFAbhinavMahajan** [comment]
any fix on this?

**Comment by HalilFocic** [comment]
> @HalilFocic got any fix on this?

I think solution will be implementing the custom managed call service for android but i did not implement it  myself.

**Comment by dkahdwk** [comment]
I'm experiencing the same issue. It's not happening on newer devices, but it's happening on older models. You can change the call settings to resolve it, but it's hard for normal users to follow suit easily.

**Comment by harrison-two** [comment]
> I'm experiencing the same issue. It's not happening on newer devices, but it's happening on older models. You can change the call settings to resolve it, but it's hard for normal users to follow suit easily.

@dkahdwk Do you mind sharing the steps of resolving it via device call settings?

**Comment by dkahdwk** [comment]
> > 나는 같은 문제를 겪고 있습니다. 최신 기기에서는 이런 현상이 발생하지 않지만, 이전 모델에서는 발생합니다. 통화 설정을 바꿔서 해결하면 되지만 일반 사용자가 쉽게 따라하기는 어렵습니다.
> 
> @dkahdwk기기 통화 설정을 통해 문제를 해결하는 단계를 공유해 주시겠어요?

Of course. But please understand that the screenshot is in Korean.

call setting > other call settings > An account that can be called > set sim for call

You can fix the settings with the default mobile phone sim on that path.

**Comment by HalilFocic** [comment]
> > > 나는 같은 문제를 겪고 있습니다. 최신 기기에서는 이런 현상이 발생하지 않지만, 이전 모델에서는 발생합니다. 통화 설정을 바꿔서 해결하면 되지만 일반 사용자가 쉽게 따라하기는 어렵습니다.
> > 
> > 
> > @dkahdwk기기 통화 설정을 통해 문제를 해결하는 단계를 공유해 주시겠어요?
> 
> Of course. But please understand that the screenshot is in Korean.
> 
> call setting > other call settings > An account that can be called > set sim for call
> 
> You can fix the settings with the default mobile phone sim on that path.

You can fiz this issue by implementing the custom cLl service on Android but documentation is not very good. But thats the answer I got 

Make custom
