### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by whenmoon** [react-native-webrtc/react-native-callkeep#65]
Should the line:

"Tell ConnectionService that the device is ready to accept outgoing calls"

not read:

"Tell ConnectionService that the device is ready to accept incoming calls"?

**Comment by manuquentin** [comment]
Hi @whenmoon 
You read correctly. The `setAvailable` method told CallKeep that our webrtc phone can make outgoing calls via the native Phone app (ios / android).

For example, when your user is logged in your application, you can call `setAvailable(true)` so when your user makes a call via the native phone app, CallKeep will pass the event through `didReceiveStartCallAction`.

But when your used log out (or the connection to your server is broken, etc..), you have to call `setAvailable(false)` so CallKeep will refuse the call and your user will not be stuck in the native UI.

**Comment by whenmoon** [comment]
Excellent explanation and thank you.
