### ISSUE TITLE
AudioRoutes value are different on different iPhones

### ISSUE THREAD

**Issue by tsminh** [react-native-webrtc/react-native-callkeep#650]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description

I wonder why `getAudioRoutes` return different values.

For example here is the result on iPhone 12:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/16502018/213075859-408f0514-9100-4fdd-9d15-db8d8ed573fb.png">

And thisthis is the result on iPhone13

<img width="191" alt="image" src="https://user-images.githubusercontent.com/16502018/213075907-b687a0d3-325d-43b5-95e2-5e116890dae8.png">

the `name` are different

I wonder if the field `name` is reliable ? or should we use `type` instead.

## Versions
    - Callkeep:
    - React Native:
    - iOS:
    - Android:
    - Phone model: 

## Logs

```
Paste here
```

**Comment by hgndgn** [comment]
I just wanted the ask same question. The return type of a "get" method should not be `void`.

In my case, I am showing the `name` when the user has to select one of the available audio routes. You also need to pass the `name` when using `setAudioRoutes(uuid: string, inputName: string)`.

**Comment by Romick2005** [comment]
@tsminh Name differs and that is obvious as you might connect samsung bluetooth headphones. Yes I agree that strange that it is not consistent for iPhones, but that is this method also provide not consistent results as it depends on currect sharable audio session category, mode and options values. So yes you should use type and also you can hardcode some names for each type as there will be no more output and input media devices than types. One name per one type.

@hgndgn Why do you need to pass name? It wouldn't be set. Media device uuid is unique and you can rely on that if you need some device tracking.

**Comment by hgndgn** [comment]
@Romick2005 Because the `setAudioRoutes` requires the name. I am using the name, when the user selects one of the possible audio routes, which I get via `getAudioRoutes`.

**Comment by Romick2005** [comment]
> @Romick2005 Because the `setAudioRoutes` requires the name. I am using the name, when the user selects one of the possible audio routes, which I get via `getAudioRoutes`. 

Oh I see... than getAudioRoutes should also return id (uuid) for each media device also.

**Comment by tsminh** [comment]
I had this done already, accept the fact that the `name` is not consistent in iPhone device.

**Comment by hgndgn** [comment]
@Romick2005 No you have to set the UUID when starting a new call (just check the doc). Media devices are identified by the `name` property in `getAudioRoutes` result
