### ISSUE TITLE
[Android] How to launch app when receive answerCall 

### ISSUE THREAD

**Issue by Poovit-B** [react-native-webrtc/react-native-callkeep#692]
## Description
I am facing an issue with opening the Android app when the user accepts a call. I have tried using the following methods: backToForeground, invokeApp, and openLink. Unfortunately, none of them seem to be working for me. I would appreciate any assistance or guidance you can provide to help me resolve this matter.

``

    const data = notificationDataRef.current?.[callUUID];
    if (!data) {
      return;
    }

    await RNCallKeep.endAllCalls();
    await RNCallKeep.backToForeground();

    await Linking.openURL('myiteleapp://');
    invokeApp({data: data});
   
``
## Versions
    - Callkeep: ^4.3.8
    - React Native: 0.70.0

**Comment by AnhQuangCee** [comment]
Same issue. Have you found  solution yet?
