### ISSUE TITLE
ringBack implementation 

### ISSUE THREAD

**Issue by folin03** [react-native-webrtc/react-native-callkeep#699]
- Reproduced on:
 - [ x ] Android
 - [ x ] iOS

## Description
I'm using react-native-callkeep, react-native-webrtc and react-native-sound to play ringBack sound on outbound call. My issue is when I call RNCallKeep.startCall(...) it silences the ringBack sound, Once I end callkeep by calling RNCallKeep.endCall(uuid) the ringBack comes back. It seems like CallKeep takes priority over audio and silences anything else. How should I implement ringBack correctly?

**Comment by wilmxre** [comment]
i used ```react-native-incall-manger``` for playing a ringback sound in outgoing calls. just call this function like this: 

```
InCallManager.start({ media: 'video', auto: true, ringback: '_BUNDLE_' }) 
```
it should be called when the ```didReceiveStartCallAction``` or ```didActivateAudioSession``` event is fired, i don't remember exactly.
when the call is connected or disconnected you will have to call ```InCallManager.stopRingback()```

**Comment by folin03** [comment]
InCallManager.startRingback(...) did the job thank you @wilmxre for pointing me the right direction.

**Comment by folin03** [comment]
InCallManager.startRingback(...) did the job thank you @wilmxre for pointing me the right direction.
