### ISSUE TITLE
[Android][Terminate]: answer call not working when app terminate/closed

### ISSUE THREAD

**Issue by AnhQuangCee** [react-native-webrtc/react-native-callkeep#716]
# Bug report

- Reproduced on: Android

## Description
Incoming call: answer call not working when app terminate (app closed) in android. My app not invoke when accept incoming call. Here in my test case.
- IOS (foreground, background, terminate): WORK.
- Android (foreground, background): WORK.
- Android (terminate/closed): DON'T WORK.

## Steps to Reproduce
When my android app terminate/closed
1. Using FCM to push notification (Incoming call).
2. Callkit in android display.
3. My app not invoke, function "answerCall" not working.

I think my app not wakeup to call function "answerCall".

## Versions
    - Callkeep: 4.3.9
    - React Native: 0.71.4
    - Android: 13
    - Phone model: Samsung Galaxy A32

Thank you for support.

## Logs

```
Paste here
```

**Comment by dkahdwk** [comment]
same issue.

And the UI that comes out when running the IncomingCall function has been changed to the system UI, can you tell me why?

**Comment by AnhQuangCee** [comment]
> same issue.
> 
> And the UI that comes out when running the IncomingCall function has been changed to the system UI, can you tell me why?

You can use function **backToForeground** to back to your app. But it only working when app foreground or background. If your app in terminate/closed state, it not working.

**Comment by AnhQuangCee** [comment]
After research few day. I have a solution.

Please note:
1. When app terminate, FCM push notif handle in function **setBackgroundMessageHandler**. You must manual setup RNCallKeep in here.
2. Using **RNCallKeep.backToForeground();** in headless (in file index.js).
3. Must call **RNCallKeep.backToForeground();** inside RNCallKeep.addEventListener('answerCall', (){});

Example:
1. In index.js
```js
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
    console.log('Message handled in the background!', remoteMessage);
    const options = {
      ios: {
        appName: 'example_app', // Your app name
      },
      android: {
        alertTitle: 'Permissions required',
        alertDescription:
          'This application needs to access your phone accounts',
        cancelButton: 'Cancel',
        okButton: 'ok',
        foregroundService: {
          channelId: 'com.example.app', // Your bundleId
          channelName: 'Foreground service for my app',
          notificationTitle: 'My app is running on background',
          notificationIcon: 'Path to the resource icon of the notification',
        },
      },
    };
    // Setup RNCallKeep manual
    RNCallKeep.registerPhoneAccount(options);
    RNCallKeep.registerAndroidEvents();
    RNCallKeep.setAvailable(true);
    
    // Displat Incoming callkit when receive Push notification
    RNCallKeep.displayIncomingCall(callUUID, number, number, 'number', false);
  });
```

2 & 3. In index.js file
```js
import {AppRegistry} from 'react-native';
import App from './App.tsx';
import {name as appName} from './app.json';
import RNCallKeep from 'react-native-callkeep';

// Call function handle notification background (example) in here
NotificationBackground();

AppRegistry.registerComponent(appName, () => App);
RNCallKeep.addEventListener('answerCall', async () => {
  // backToForeground only working inside loop or you can use setTimeout to invoke it.
  for (var i = 0; i < 10; i++) {
    // This function will be wakeup your app
    RNCallKeep.backToForeground();
  }
  RNCallKeep.removeEventListener('answerCall');
});

```

**Comment by GlennAzx** [comment]
may i know what the solution was to backToForeground when app is terminated/closed state
