### ISSUE TITLE
Sending `RNCallKeepDidChangeAudioRoute` with no listeners registered

### ISSUE THREAD

**Issue by sametcl2** [react-native-webrtc/react-native-callkeep#735]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description

In iOS CallKit screen shows up. After answering call I got the error Sending `RNCallKeepDidChangeAudioRoute` with no listeners registered.

## Versions
    - Callkeep: 4.3.12
    - React Native: 0.71.1
    - iOS: 15.7
    - Android:
    - Phone model: iPhone 7

## Logs

```
Sending `RNCallKeepDidChangeAudioRoute` with no listeners registered.
```

**Comment by stevenbdf** [comment]
@sametcl2 I'm experiencing the same behavior, were you able to figure out why this happens?

**Comment by geoffcfchen** [comment]
when I was using only react-native-webrtc, I did not see this warning. However, right after installing react-native-callkeep, I started seeing this warning message even though I did not modify any of the code yet.

**Comment by sametcl2** [comment]
@geoffcfchen is this warning preventing trigger of answerCall event?

**Comment by stevenbdf** [comment]
This issue happened on my send because I was answering a phone call in AppDelegate files before the RN code started. 
This was caused by me having setup VoIP in iOS native code, so I instead let the JS part handle the VoIP registration of the device. It added some delay than the previous solution but this warning went away and I was able to answer the call properly

**Comment by sametcl2** [comment]
> This issue happened on my end because I was answering a phone call in AppDelegate files before the RN code started. This was caused by me having setup VoIP in iOS native code, so I instead let the JS part handle the VoIP registration of the device. It added some delay than the previous solution but this warning went away and I was able to answer the call properly

Hi @stevenbdf thanks for your answer. How did you register in js side. Can you give me example please?

**Comment by kr-yeon** [comment]
Hello @stevenbdf! Thank you for comment. I understand that iOS needs to run Callkeep as quickly as possible. Otherwise, I understand that the app will be terminated. In this situation, how can I use a method to launch Callkeep after the jsBundle is loaded without the app closing?

**Comment by stevenbdf** [comment]
> Hello @stevenbdf! Thank you for comment. I understand that iOS needs to run Callkeep as quickly as possible. Otherwise, I understand that the app will be terminated. In this situation, how can I use a method to launch Callkeep after the jsBundle is loaded without the app closing?

I think that's the recommendation from iOS yes. But from what I was able to experiment in my app, it is not mandatory. I had to remove the `voipRegistration` from the delegate file and I simply initially RNCallkeep in my React Native code. It can be done inside a screen, provider or layout that you make sure it's rendered when your app is awaken from background mode. In my case I put and invoke the `RNCallKeep.setup(callKeepOptions)` in a navigation Provider that's only rendered when the user is logged in. 

`AppDelegate.mm`
![image](https://github.com/react-native-webrtc/react-native-callkeep/assets/35903969/b5998a06-d2cf-46bb-9991-574a220223a1)

`authenticated-navigation.tsx`
![image](https://github.com/react-native-webrtc/react-native-callkeep/assets/35903969/0234bb97-6868-49f2-a646-964f64253e32)

**Comment by kr-yeon** [comment]
> > 안녕하세요@stevenbdf! 의견을 보내주셔서 감사합니다. iOS에서는 Callkeep을 최대한 빨리 실행해야 한다는 점을 이해합니다. 그렇지 않으면 앱이 종료되는 것으로 알고 있습니다. 이 상황에서 jsBundle이 로드된 후 앱을 닫지 않고 Callkeep을 시작하는 메서드를 어떻게 사용할 수 있습니까?
> 
> 나는 그것이 iOS의 권장 사항이라고 생각합니다. 하지만 내 앱에서 실험해 본 결과 필수는 아닙니다. `voipRegistration`위임 파일에서 를 제거해야 했고 처음에는 React Native 코드에서 RNCallkeep을 사용했습니다. 앱이 백그라운드 모드에서 깨어날 때 렌더링되는지 확인하는 화면, 공급자 또는 레이아웃 내에서 수행할 수 있습니다. `RNCallKeep.setup(callKeepOptions)`제 경우에는 사용자가 로그인할 때만 렌더링되는 탐색 제공자에 를 넣고 호출했습니다 .
> 
> `AppDelegate.mm` ![영상](https://private-user-images.githubusercontent.com/35903969/289712612-b5998a06-d2cf-46bb-9991-574a220223a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDQ1NzYsIm5iZiI6MTcwMjM0NDI3NiwicGF0aCI6Ii8zNTkwMzk2OS8yODk3MTI2MTItYjU5OThhMDYtZDJjZi00NmJiLTk5OTEtNTc0YTIyMDIyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxMjQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MmEzYTNhMjFiZTI4MjdhNThlMzAwOWFhNTAzNjY4MWMyOGM2NTA2MzU5NGFlMThiZTdiZTgwYmQzZWM4MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._T6ExUCw4gTlOGzp9rK9f8V0P9T6Q_VgW4XTxqZUzBk)
> 
> `authenticated-navigation.tsx` ![영상](https://private-user-images.githubusercontent.com/35903969/289712985-0234bb97-6868-49f2-a646-964f64253e32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDQ1NzYsIm5iZiI6MTcwMjM0NDI3NiwicGF0aCI6Ii8zNTkwMzk2OS8yODk3MTI5ODUtMDIzNGJiOTctNjg2OC00OWYyLWE2NDYtOTY0ZjY0MjUzZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxMjQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzNlMDlhYjQ4ZDE3ZTBkYmFhZDQ1OWIxYmZkZTc4YTFhZTdiZWI4MzAzNDE2ZmQxZGQ0ZDVlNmE5YmQ1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e0tUxfEqT8Mw3_CFwDtXWRAzRtx_Fd3xbRMMa-Y79yA)

Hmm... thank you. I'm having a lot of worries.

**Comment by kr-yeon** [comment]
> > Hello @stevenbdf! Thank you for comment. I understand that iOS needs to run Callkeep as quickly as possible. Otherwise, I understand that the app will be terminated. In this situation, how can I use a method to launch Callkeep after the jsBundle is loaded without the app closing?
> 
> I think that's the recommendation from iOS yes. But from what I was able to experiment in my app, it is not mandatory. I had to remove the `voipRegistration` from the delegate file and I simply initially RNCallkeep in my React Native code. It can be done inside a screen, provider or layout that you make sure it's rendered when your app is awaken from background mode. In my case I put and invoke the `RNCallKeep.setup(callKeepOptions)` in a navigation Provider that's only rendered when the user is logged in.
> 
> `AppDelegate.mm` ![image](https://private-user-images.githubusercontent.com/35903969/289712612-b5998a06-d2cf-46bb-9991-574a220223a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTI5MzQsIm5iZiI6MTcwMjM1MjYzNCwicGF0aCI6Ii8zNTkwMzk2OS8yODk3MTI2MTItYjU5OThhMDYtZDJjZi00NmJiLTk5OTEtNTc0YTIyMDIyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAzNDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNzUzMWRkMDg0MTcyYWMwMWQwOTJlNzc1ZDMyZjYwODFhNWIwZWJlZGNjY2FlNGQ5YWM3OTg4NTFhNGE2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlgF4rCFAqqF0YITxt_UZHdnki6JcxXEVN8Ka5gQ4TM)
> 
> `authenticated-navigation.tsx` ![image](https://private-user-images.githubusercontent.com/35903969/289712985-0234bb97-6868-49f2-a646-964f64253e32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTI5MzQsIm5iZiI6MTcwMjM1MjYzNCwicGF0aCI6Ii8zNTkwMzk2OS8yODk3MTI5ODUtMDIzNGJiOTctNjg2OC00OWYyLWE2NDYtOTY0ZjY0MjUzZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAzNDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MzZmODhjMzkwMzY2MWZmMDE4ZDNiNDliZTA2YjQ4OGQwZTg0NzRjNDA0ZTU0M2IwMDU1MGQ1ZTM0ZDE1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8rQzwrVjSwllpO4YOZFLxrpPGhh-UK0yaEop318ixTc)

@stevenbdf 
Your solution works as expected. It's amazing. Thank you. It seems that the call is executed after all event listeners are ready. Is there a possibility that bundling may be delayed?

**Comment by bilal-korir** [comment]
1. If you want to listen to the event and do something with it, then call:

```
    DeviceEventEmitter.addListener('RNCallKeepDidChangeAudioRoute', data => {
      console.log(data)
    })

    RNCallKeep.addEventListener('didChangeAudioRoute', ({ output }) => {
      console.log(output)
    })
```

2. If you want to silence/hide the warning, then call:

```
    DeviceEventEmitter.removeAllListeners('RNCallKeepDidChangeAudioRoute')
    DeviceEventEmitter.removeAllListeners('didChangeAudioRoute')
```
