### ISSUE TITLE
iOS 16 app is not opening after answering in lockscreen

### ISSUE THREAD

**Issue by sametcl2** [react-native-webrtc/react-native-callkeep#736]
In iOS 16 and above, the app does not open after answering the call. When I tried in iOS 15.7, it opened the app after answering the call.

**Comment by neetable-abhilash** [comment]
Iam facing the same issue need urgent help.

**Comment by sametcl2** [comment]
> I am facing the same issue need urgent help. For me it's working sometimes but frequently not working.

Me too, it worked correctly a couple of times but mostly did not work.

**Comment by neetable-abhilash** [comment]
> > I am facing the same issue need urgent help. For me it's working sometimes but frequently not working.
> 
> Me too, it worked correctly a couple of times but mostly did not work.

seems like there is an issue with answerCall() sometimes not getting triggered when app is in background.

**Comment by sametcl2** [comment]
> > > I am facing the same issue need urgent help. For me it's working sometimes but frequently not working.
> > 
> > 
> > Me too, it worked correctly a couple of times but mostly did not work.
> 
> seems like there is an issue with answerCall() sometimes not getting triggered when app is in background.

Have you found any solution? Looks like there is a problem with iOS 16.

**Comment by neetable-abhilash** [comment]
Try registering the events in main screen it worked for me.

**Comment by sametcl2** [comment]
> Try registering the events in main screen it worked for me.

Actually, I couldn't get the idea of registering events on main screen. it's OK on iOS 15.7?

**Comment by MinhThu100200** [comment]
I am also facing this issue. =(((

**Comment by MinhThu100200** [comment]
> @manuquentin @ianlin @aarkalyk Hi, do you have any idea about this problem?

hi, I found my issue because when client answer call immediately I call endCall event to turn off default call screen and naviagte to my callscreen in my application. So I change my flow after navigation to my callscreen, I will call endCall event. It work for me

**Comment by shivo-ham** [comment]
working in Iphone8 but not working in Iphone12 @sametcl2

**Comment by sametcl2** [comment]
@shivo-ham  Actually, I moved voip code to js side from the native side. After that, I controlled endCall event like @MinhThu100200. My issue seems resolved after these.

**Comment by samp84531** [comment]
@sametcl2  do mean about native code? **native side.**

**Comment by shivo-ham** [comment]
@sametcl2 do you mean about native code? native side.

**Comment by samp84531** [comment]
@sametcl2  My app is not opening in killed state when the user accepting  the call

**Comment by shivo-ham** [comment]
@sametcl2 My app is not opening in a killed state when the user accepts the call

**Comment by shivo-ham** [comment]
@sametcl2  Did you also add Voip notifications to CallKeep?

**Comment by sametcl2** [comment]
@shivo-ham yes native side, you should use voip notifications with callkeep

**Comment by shivo-ham** [comment]
OK Thanks

**Comment by shivo-ham** [comment]
@sametcl2  VoIP call is also not working for me, Can you please check this link, I have raised an issue in stackoverflow

https://stackoverflow.com/questions/77414647/react-native-voip-push-notification-app-doesnt-launch-after-accepting-a-call
