### ISSUE TITLE
No calling UI when receiving a call on iOS 17.1.1

### ISSUE THREAD

**Issue by ivergot-rc** [react-native-webrtc/react-native-callkeep#750]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description
I'm running a React Native app that supports video calling through WebRTC, I'm also using react-native-voip-push-notification.
- After the phone is turned on/restarted the first call works fine, the native call screen is shown and I am able to answer it.
- EndCall methods are triggered and executed, no exceptions are thrown (that I can detect)
- But, when I make the second call the phone rings, the video call icon is shown in the notification tray at the top of the screen but no call screen UI is shown and I cannot answer the call
- I've checked, _"onDidDisplayIncomingCall"_ is triggered, without errors in the payload, but like I said there is no calling UI, just the ringtone and the notification icon
- Restarting or even reinstaling the app doesn't help
- After restarting the phone, only the first call works, then the same thing happens again

**NOTE**: I started getting this issue after upgrading to the **iOS version 17.1.1.**

## Steps to Reproduce
Upgrade to iOS 17.1.1
Establish multiple calls in a row.

## Versions
    - Callkeep: tested both on 4.3.6 and 4.3.12
    - React Native: 0.71.2
    - iOS: 17.1.1
    - Android: /
    - Phone model: iPhone XS, iPhone 12 mini

## Logs

```

```

**Comment by ivergot-rc** [comment]
For everyone else who will stumble to the same issue and to answer my own question I think I figured out what was wrong.
Before iOS 17.1 the call UUID didn't need to be unique for everything to work, and now it has to. In my example, the UUID was caller ID from the database and it all worked (and still does!) fine on all devices prior to 17.1. After I changed my code to generate a new UUID for each call, everything returned to normal.

**Comment by booncoder123** [comment]
> For everyone else who will stumble to the same issue and to answer my own question I think I figured out what was wrong. Before iOS 17.1 the call UUID didn't need to be unique for everything to work, and now it has to. In my example, the UUID was caller ID from the database and it all worked (and still does!) fine on all devices prior to 17.1. After I changed my code to generate a new UUID for each call, everything returned to normal.

this is work!

**Comment by disco-panda** [comment]
@booncoder123 Good catch, if this is working, would you mind closing?
