### ISSUE TITLE
call keep crash : index 0 beyond bounds for empty array

### ISSUE THREAD

**Issue by fukemy** [react-native-webrtc/react-native-callkeep#755]
# Bug report

- [x] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [ ] Android
 - [x] iOS

## Description

Fatal Exception: NSRangeException
*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty array

## Steps to Reproduce
  answer the call then got this error

## Versions
    - Callkeep: 4.3.12
    - React Native: 0.72.5
    - iOS: 17.0.3
    - Android: NO
    - Phone model: IOS

## Logs

```
Fatal Exception: NSRangeException
*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty array
0
CoreFoundation
__exceptionPreprocess
2
CoreFoundation
-[__NSArray0 objectEnumerator]
3
VedaxLink
RNCallKeep.m - Line 182
+[RNCallKeep getAudioOutput] + 182
4
VedaxLink
RNCallKeep.m - Line 141
-[RNCallKeep onAudioRouteChange:] + 141
5
CoreFoundation
__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
20
UIKitCore
UIApplicationMain
21
VedaxLink
main.m - Line 8
main + 8
22
(Missing)
```

**Comment by CaptainJeff** [comment]
Same issue here

**Comment by h4rshil** [comment]
We are getting same issue,

**Comment by Pikkurthi** [comment]
I got this same error in Expo, I am using eas to build the project, How to fix this in expo?
