### ISSUE TITLE
[Android] One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when receiving call when targetSdkVersion is 34

### ISSUE THREAD

**Issue by taekeun-two** [react-native-webrtc/react-native-callkeep#780]
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [X] Android
 - [ ] iOS

## Description

After upgrading

* from: ReactNative `0.72.X` and Expo `49`,
* to: ReactNative `0.73.X` and Expo `50`,

```
// android/build.gradle

buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlinVersion = "1.8.0"
    }
```

the following error occurs whenever receiving call in Android 14 platform phone.

```
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified 
```

### References

Registering receivers with intention using the `RECEIVER_EXPORTED` / `RECEIVER_NOT_EXPORTED` flag was introduced as part of Android 13 and is now a requirement for apps running on Android 14 or higher (U+). 
It seems that it should be applied for callkeep's registering receivers.

* https://stackoverflow.com/questions/77235063/one-of-receiver-exported-or-receiver-not-exported-should-be-specified-when-a-rec
* https://github.com/joltup/rn-fetch-blob/issues/866#issuecomment-2030940568

```
diff --git a/node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java b/node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java
index a8abd71..efa1b46 100644
--- a/node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java
+++ b/node_modules/rn-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java
@@ -196,7 +196,11 @@ public class RNFetchBlobReq extends BroadcastReceiver implements Runnable {
                 DownloadManager dm = (DownloadManager) appCtx.getSystemService(Context.DOWNLOAD_SERVICE);
                 downloadManagerId = dm.enqueue(req);
                 androidDownloadManagerTaskTable.put(taskId, Long.valueOf(downloadManagerId));
-                appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE));
+                if (Build.VERSION.SDK_INT >= 34 && appCtx.getApplicationInfo().targetSdkVersion >= 34) {
+                  appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE), Context.RECEIVER_EXPORTED);
+                }else{
+                  appCtx.registerReceiver(this, new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE));
+                }
                 return;
             }
```

## Steps to Reproduce

* Upgrade to react native 0.73.8 and Expo 50.0.18
* Receiving call in Android 14 platform phone. It always occurs.

## Versions
    - Callkeep: 4.3.9
    - React Native: 0.73.8   // upgraded from 0.72.10
    - Expo : 50.0.18         // upgraded from 49
    - iOS:
    - Android: Android version 14
    - Phone model: Samsung Galaxy S23+ SM-S916N

## Logs

```
java.lang.SecurityException: <packageName>: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
```

![iScreen Shoter - Microsoft Teams - 240527101342](https://github.com/react-native-webrtc/react-native-callkeep/assets/133075566/65ac0d5f-9529-4a0c-9fad-4ee756ae98b1)

**Comment by taekeun-two** [comment]
Initially I thought that it's callkeep's code, but finally I found that the error comes from `react-native-incall-manager`. I'm so sorry for wrong error report.

![image](https://github.com/user-attachments/assets/b5ea69e2-95d6-4ebb-a3a2-03c90028b36b)

In `react-native-incall-manger` latest `v4.2.0` , this problem was fixed.

https://github.com/react-native-webrtc/react-native-incall-manager/releases/tag/4.2.0

```
Support Android 14 receiver changes
fix(android): specify export mode on BroadcastReceivers ( Santhosh Vaiyapuri 2024-02-16 10:41:22 +0100)
```

**Comment by kingmuffy** [comment]
thank you, this helped

**Comment by rajeshfullestop** [comment]
I have used the rn-fetch-blob package. I implemented the download code and it is working correctly on iOS. But when I try to download a PDF on Android, I get an error. Please give me a solution. I have attached the screenshot.

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

![Image](https://github.com/user-attachments/assets/1ee03ab2-d6d3-4e28-b5db-7c58adc7ec9e)
