### ISSUE TITLE
No Audio on iOS

### ISSUE THREAD

**Issue by NIyerAD** [react-native-webrtc/react-native-callkeep#84]
"react-native-callkeep": "^2.0.3"
"react-native-webrtc": "^1.75.0"

I am not receiving any audio when I answer an inbound call on iOS (android is fine). I do get the following in the logs. 
_[RNCallKeep][configureAudioSession] Activating audio session_
_[RNCallKeep][CXProviderDelegate][provider:didActivateAudioSession]_

**Comment by rcidt** [comment]
I am getting the same thing. It definitely has to do with the Audio Session. I think the call will have no audio if SIP call is established _before_ the Audio Session is activated. 

I am trying to only start accept/make calls once the `didActivateAudioSession` event fires, but I can only get it to fire once. Looking into a solution.

**Comment by NIyerAD** [comment]
Thanks for your help, @rcidt. I thought it may have been something to do with the audio session. I'm handling the call after `didActivateAudioSession` event fires but there's still no audio. This happens when the first incoming call arrives so I don't think that it's an issue with ending all of the calls first.

**Comment by ashirkhan94** [comment]
Hi,
Any update on this
thanks in advance

**Comment by abpbackup** [comment]
Same here

**Comment by ssimoe50** [comment]
I was looking for similar issues to mine. I found this one. Honestly it didn't fix my issue, but put me in a different perspective.
So in a way it help me rethink my normal approach when working with CallKeep and WebRTC ***on iOS*** (on Android I've a custom integrated dialer and call UI so I don't use Callkeep). I got 2 service files: CallkeepService (for all the listeners and events) and DialerService (for all the WebRTC and Audio management)

For other people that might face it here is what I've done:
* I've completely rework my call flow for iOS only. On Android, didn't had any issues. So this is focus only on iOS keep that in mind...
* When I receive my first notification, a VoIP notification (highly recommended!), I add the Callkeep code, initialize/setup and to display the call UI from Apple's CallKit directly on the AppDelegate. --> See `react-native-voip-push-notification` to be able to use Apple's PushKit for VoIP.
* Implement the Callkeep listeners as soon as possible (I've went with the root `index.js`on my project, just import my CallkeepService  and call the setup method). Important to not forget to implement the `didLoadWithEvents` listener for when the app has been manually or forced close (ie. not in background, so completely closed), so when the app loads you can get the events that have been triggered prior to JS startup. (Usually you'll have at least 3 important events to look: `RNCallKeepDidDisplayIncomingCall`,`RNCallKeepPerformAnswerCallAction`,`RNCallKeepPerformEndCallAction`).
* These 3 events from the listener `didLoadWithEvents` or both `answerCall` and `endCall` listeners are related to the user actions on the Apple's CallKit (ie. call screen).
* While the device is handling the actions on CallKit, you might already be receiving some background notifications related to the WebRTC process, ***don't*** process anything or signal back anything just yet! (This is where I was mostly doing it wrong! I was creating the `peerconnection`, even tho I wasn't yet adding tracks or the `localdescription`...)
* So I just store all the data `offer` and all the `candidates` on my DialerService file, but I didn't do anything yet!
* Only ***after*** the `answerCall` or the `RNCallKeepPerformAnswerCallAction` (when the user has answered on Apple's CallKit) I will start to process the `offer` and all the `candidates` , and after of course signal back with an `answer`.
* And then just follow the "normal" WebRTC process.
* Important to alert too, that I don't use any audio methods from CallKeep! All the audio management I do using `react-native-incall-manager`. This is so much better!
* On my DialerService file I really only use 3 methods from Callkeep: `RNCallKeep.rejectCall`, `RNCallKeep.endCall`, `RNCallKeep.endCalls` (this last one it's on my clean up method just in case something got stuck).


Well this is more or less what I did! I spent 4 full days working on this, I'm writing here at the very end and late in the night, so I apologize if my train though is a little messy and confusing, but I think I got most of it out.

Hope this might help someone else, other than me!
Cheers mates!

**Comment by haisamMH** [comment]
We are having a similar issue, but what we tried to achieve is a bit different from the above scenarios.

We wanted to gather all ice candidates while presenting the incoming call screen with CallKit, so we created a pre-answer flow that creates a peer connection and gathers candidates. 

But there is no audio after the call is answered, and we can't hear anything from the other side.
