### ISSUE TITLE
Android: Can't get past answer screen.

### ISSUE THREAD

**Issue by danwhite-ad** [react-native-webrtc/react-native-callkeep#88]
React-Native: **v0.59.8**
React-Native-Callkeep: **v3.0.1**
React-Native-WebRTC: **v1.69.2**
Android: **Pie**

When an inbound call is started with `RNCallKeep.displayIncomingCall(this.getCurrentCallId(), number, name);` the answer dropdown appears and when the answer button is clicked the app navigates to a full screen native answer screen. No matter how many times I attempt to answer the screen goes blank and returns to the answer screen. The `answerCall` method fires every time.

**Comment by whenmoon** [comment]
@danwhite-ad Did you manage to find the problem?

**Comment by danwhite-ad** [comment]
It turned out to be an issue with our sip instance, not related to the package. Thats why I closed the issue soon after opening.
