### ISSUE TITLE
Android : Unable to view permission dialog & call UI

### ISSUE THREAD

**Issue by msuma268** [react-native-webrtc/react-native-callkeep#89]
Started using CallKeep since last week. With v2.0.3, I was able to view Android permission alert text configured while setting up CallKit and on invoking startCall, call screen too used to appear if phone account permission was granted. 

Upgraded to latest version today(v3.0.1). On invoking RNCallKeep.setup(), I am able to view only System alert "Allow <App Name> to make and manage phone calls?". On tapping "Allow", nothing happens i.e, configured alert text is no longer shown. However, App name is listed in Calling Accounts (with disabled state). If I manually go to Calling accounts and grant access to app and try to place a call, no longer able to view call screen. 

Configuration set up is done as below:
static setup() {
        const options = {
            ios: {
                appName: 'App',
            },
            android: {
                alertTitle: 'App Permissions',
                alertDescription: 'This application needs access your phone accounts',
                cancelButton: 'Cancel',
                okButton: 'Ok',
            }
        };

        try {
            RNCallKeep.setup(options);
            RNCallKeep.setAvailable(true); 
        } catch (err) {
            Log.debug(TAG, 'initializeCallKeep error:', err.message);
        }
    }
I am invoking all CallKeep APIs from js files which are not components. Does that matter?
I have tested this on OS 6.0.1 and 9.0

Can you let me know what I am missing here ?

**Comment by manuquentin** [comment]
Hi @msuma268, can you check the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) and see what's different from your code ?

**Comment by msuma268** [comment]
Hi @manuquentin, I added logic to invoke setup on app launch and handled additional permissions required by sip client I am using , post which call screens are appearing as expected.
