### ISSUE TITLE
indes.d.ts file isnt in sync with CallKeep APIs

### ISSUE THREAD

**Issue by msuma268** [react-native-webrtc/react-native-callkeep#90]
API signatures in index.d.ts and the one supported by latest CallKeep version are not in sync.

Ex: setCurrentCallActive takes call UUID as argument in latest version. But in index.d.ts, setCurrentCallActive is declared with no arguments. If typescript check is enabled on the javascript. then error is shown in IDE with prompt to invoke method without any arguments.

There is no updateDisplay API available in index.d.ts..

**Comment by manuquentin** [comment]
Fixed in #96
