### ISSUE TITLE
Unable to view CallKeep logs in Android

### ISSUE THREAD

**Issue by msuma268** [react-native-webrtc/react-native-callkeep#91]
I am unable to view any CallKeep logs in Android. Using the command "adb logcat *:S RNCallKeepModule:V" as suggested, but no logs are getting printed.  Tested this in OS 6.0.1 and 9.0. Is there any additional configuration that needs to be done to be able to view the logs

**Comment by hmharshit** [comment]
You can use this command to view the logs
`react-native log-android`
